import type { Restaurant } from './types';

export const allRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'The Golden Spoon',
    slug: 'the-golden-spoon',
    imageId: 'restaurant-1',
    cuisine: 'Italian',
    rating: 4.7,
    reviews: 1204,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Italian', 'Pasta', 'Pizza'],
    menu: [
      {
        title: 'Appetizers',
        items: [
          { id: '101', name: 'Bruschetta', description: 'Toasted ciabatta bread topped with fresh diced tomatoes, garlic, basil, and a drizzle of balsamic glaze.', price: 8.99, imageId: 'food-1' },
          { id: '102', name: 'Calamari Fritti', description: 'Tender squid, lightly battered and fried to a golden brown. Served with a zesty marinara sauce and a lemon wedge.', price: 12.99, imageId: 'food-2' },
        ],
      },
      {
        title: 'Main Courses',
        items: [
          { id: '103', name: 'Spaghetti Carbonara', description: 'Classic spaghetti tossed in a creamy sauce made with fresh eggs, Pecorino Romano cheese, crispy pancetta, and freshly ground black pepper.', price: 18.99, imageId: 'food-3' },
          { id: '104', name: 'Margherita Pizza', description: 'A timeless classic featuring a thin crust, San Marzano tomato sauce, fresh mozzarella, basil leaves, and a drizzle of extra virgin olive oil.', price: 15.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Sushi Palace',
    slug: 'sushi-palace',
    imageId: 'restaurant-2',
    cuisine: 'Japanese',
    rating: 4.9,
    reviews: 2345,
    deliveryTime: 30,
    deliveryFee: 4.50,
    categories: ['Japanese', 'Sushi', 'Asian'],
    menu: [
      {
        title: 'Sushi Rolls',
        items: [
          { id: '201', name: 'California Roll', description: 'A favorite for a reason. Made with imitation crab, creamy avocado, and crisp cucumber, all rolled in seaweed and seasoned rice.', price: 10.99, imageId: 'food-5' },
          { id: '202', name: 'Spicy Tuna Roll', description: 'A flavorful roll with chopped fresh tuna, spicy mayo, and cucumber, finished with a sprinkle of sesame seeds.', price: 12.99, imageId: 'food-6' },
        ],
      },
      {
        title: 'Nigiri',
        items: [
          { id: '203', name: 'Salmon Nigiri', description: 'A slice of buttery, fresh salmon served over a hand-pressed bed of seasoned sushi rice.', price: 6.99, imageId: 'food-7' },
          { id: '204', name: 'Tuna Nigiri', description: 'Premium, melt-in-your-mouth tuna delicately placed atop a small mound of vinegared rice.', price: 7.99, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Burger Bonanza',
    slug: 'burger-bonanza',
    imageId: 'restaurant-3',
    cuisine: 'American',
    rating: 4.5,
    reviews: 876,
    deliveryTime: 20,
    deliveryFee: 1.99,
    categories: ['American', 'Burgers', 'Fast Food'],
    menu: [
      {
        title: 'Burgers',
        items: [
          { id: '301', name: 'Classic Cheeseburger', description: 'A juicy, all-beef patty grilled to perfection, topped with melted American cheese, crisp lettuce, fresh tomato, and sliced onion on a toasted sesame seed bun.', price: 11.99, imageId: 'food-9' },
          { id: '302', name: 'Bacon Avocado Burger', description: 'A juicy beef patty topped with crispy bacon, creamy avocado, and melted swiss cheese, served on a toasted brioche bun with lettuce and tomato. A truly satisfying burger experience.', price: 14.99, imageId: 'food-10' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '303', name: 'French Fries', description: 'Golden, crispy fries salted to perfection. The perfect companion to any burger.', price: 4.99, imageId: 'food-11' },
          { id: '304', name: 'Onion Rings', description: 'Thick-cut onion rings, battered and fried until golden and crispy. Served with a side of house dipping sauce.', price: 5.99, imageId: 'food-12' },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Taco Town',
    slug: 'taco-town',
    imageId: 'restaurant-4',
    cuisine: 'Mexican',
    rating: 4.6,
    reviews: 998,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Mexican', 'Tacos', 'Burritos'],
    menu: [
       {
        title: 'Tacos',
        items: [
          { id: '401', name: 'Carne Asada Taco', description: 'Tender, marinated grilled steak served in a warm corn tortilla with fresh cilantro and onions.', price: 3.99, imageId: 'food-13' },
          { id: '402', name: 'Al Pastor Taco', description: 'Savory marinated pork, slow-cooked on a vertical spit, and served with a slice of pineapple, cilantro, and onions.', price: 3.99, imageId: 'food-14' },
        ],
      },
      {
        title: 'Burritos',
        items: [
          { id: '403', name: 'Bean & Cheese Burrito', description: 'A simple yet satisfying classic. Creamy refried beans and melted cheese wrapped in a warm flour tortilla.', price: 8.99, imageId: 'food-15' },
          { id: '404', name: 'California Burrito', description: 'A Southern California icon. Packed with juicy carne asada, crispy french fries, shredded cheese, and creamy guacamole.', price: 12.99, imageId: 'food-16' },
        ],
      },
    ],
  },
  {
    id: '5',
    name: 'Curry House',
    slug: 'curry-house',
    imageId: 'restaurant-5',
    cuisine: 'Indian',
    rating: 4.8,
    reviews: 1543,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Indian', 'Curry', 'Vegetarian'],
    menu: [
       {
        title: 'Curries',
        items: [
          { id: '501', name: 'Chicken Tikka Masala', description: 'Tender chunks of grilled chicken simmered in a rich, creamy tomato-based sauce with a blend of aromatic spices.', price: 16.99, imageId: 'food-17' },
          { id: '502', name: 'Paneer Butter Masala', description: 'Soft cubes of Indian cottage cheese (paneer) cooked in a luscious, buttery tomato sauce with cream and spices.', price: 15.99, imageId: 'food-18' },
        ],
      },
      {
        title: 'Breads',
        items: [
          { id: '503', name: 'Garlic Naan', description: 'Soft, leavened flatbread freshly baked in a tandoor oven, brushed with garlic-infused butter.', price: 3.99, imageId: 'food-19' },
          { id: '504', name: 'Roti', description: 'A simple, healthy whole wheat flatbread, cooked on a griddle. The perfect partner for any curry.', price: 2.99, imageId: 'food-20' },
        ],
      },
    ],
  },
  {
    id: '6',
    name: 'The Green Bowl',
    slug: 'the-green-bowl',
    imageId: 'restaurant-6',
    cuisine: 'Salads',
    rating: 4.9,
    reviews: 789,
    deliveryTime: 15,
    deliveryFee: 2.50,
    categories: ['Salads', 'Healthy', 'Vegan'],
    menu: [
       {
        title: 'Signature Salads',
        items: [
          { id: '601', name: 'Cobb Salad', description: 'A hearty salad with mixed greens, grilled chicken, crispy bacon, hard-boiled egg, avocado, tomatoes, and blue cheese crumbles.', price: 14.99, imageId: 'food-21' },
          { id: '602', name: 'Quinoa & Avocado Power Bowl', description: 'A nutrient-packed bowl of quinoa, creamy avocado, protein-rich chickpeas, and mixed greens with a zesty lemon vinaigrette.', price: 13.99, imageId: 'food-22' },
        ],
      },
      {
        title: 'Create Your Own',
        items: [
          { id: '603', name: 'Custom Salad', description: 'Your salad, your way. Choose your base, select up to five fresh toppings, and finish with your favorite dressing.', price: 15.99, imageId: 'food-23' },
        ],
      },
    ],
  },
  {
    id: '7',
    name: 'The Noodle Bar',
    slug: 'the-noodle-bar',
    imageId: 'restaurant-7',
    cuisine: 'Vietnamese',
    rating: 4.7,
    reviews: 890,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Vietnamese', 'Noodles', 'Pho'],
    menu: [
      {
        title: 'Pho',
        items: [
          { id: '701', name: 'Classic Beef Pho', description: 'A comforting bowl of rich beef broth, slow-simmered for hours, served with rice noodles, thin slices of beef, and fresh herbs.', price: 13.99, imageId: 'food-28' },
          { id: '702', name: 'Chicken Pho', description: 'A lighter yet deeply savory chicken broth with tender shredded chicken, rice noodles, and a garnish of cilantro and onion.', price: 12.99, imageId: 'food-29' },
        ],
      },
      {
        title: 'Appetizers',
        items: [
          { id: '703', name: 'Fresh Spring Rolls', description: 'Delicate rice paper rolls filled with shrimp, pork, vermicelli noodles, and fresh herbs. Served with a peanut dipping sauce.', price: 7.99, imageId: 'food-26' },
        ],
      },
    ],
  },
  {
    id: '8',
    name: 'Pizza Planet',
    slug: 'pizza-planet',
    imageId: 'restaurant-8',
    cuisine: 'Pizza',
    rating: 4.4,
    reviews: 654,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Pizza', 'Italian', 'Fast Food'],
    menu: [
      {
        title: 'Specialty Pizzas',
        items: [
          { id: '801', name: 'Pepperoni Overload', description: 'A pepperoni lover\'s dream. Edge-to-edge coverage of classic spicy pepperoni slices over mozzarella and our signature tomato sauce.', price: 17.99, imageId: 'food-30' },
          { id: '802', name: 'Veggie Supreme', description: 'A garden on a pizza! Loaded with fresh bell peppers, red onions, black olives, and mushrooms on a bed of mozzarella.', price: 16.99, imageId: 'food-31' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '803', name: 'Garlic Knots', description: 'Soft, warm dough knots tossed in garlic butter and parmesan cheese. Served with a side of classic marinara sauce.', price: 6.99, imageId: 'food-32' },
        ],
      },
    ],
  },
  {
    id: '9',
    name: 'The Daily Grind',
    slug: 'the-daily-grind',
    imageId: 'restaurant-9',
    cuisine: 'Cafe',
    rating: 4.8,
    reviews: 1102,
    deliveryTime: 10,
    deliveryFee: 1.50,
    categories: ['Coffee', 'Cafe', 'Breakfast'],
    menu: [
      {
        title: 'Coffee & Tea',
        items: [
          { id: '901', name: 'Iced Latte', description: 'Rich, smooth espresso combined with chilled milk and served over ice. A refreshing classic.', price: 4.99, imageId: 'food-33' },
          { id: '902', name: 'Matcha Green Tea', description: 'Vibrant, ceremonial grade matcha powder whisked with steamed milk for a creamy, earthy, and energizing beverage.', price: 5.49, imageId: 'food-34' },
        ],
      },
      {
        title: 'Pastries',
        items: [
          { id: '903', name: 'Croissant', description: 'A perfectly baked, buttery, and flaky croissant with a soft, airy interior. Pairs perfectly with any coffee.', price: 3.50, imageId: 'food-35' },
        ],
      },
    ],
  },
  {
    id: '10',
    name: 'Bangkok Spice',
    slug: 'bangkok-spice',
    imageId: 'restaurant-10',
    cuisine: 'Thai',
    rating: 4.6,
    reviews: 932,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Thai', 'Curry', 'Asian'],
    menu: [
      {
        title: 'Main Dishes',
        items: [
          { id: '1001', name: 'Pad Thai', description: 'Thailand\'s most famous noodle dish! Stir-fried rice noodles with shrimp, tofu, bean sprouts, and crushed peanuts in a tangy tamarind sauce.', price: 15.99, imageId: 'food-36' },
          { id: '1002', name: 'Green Curry', description: 'A fiery and aromatic green curry made with coconut milk, chicken, bamboo shoots, bell peppers, and fresh basil.', price: 16.99, imageId: 'food-37' },
        ],
      },
      {
        title: 'Appetizers',
        items: [
          { id: '1003', name: 'Tom Yum Soup', description: 'A classic hot and sour soup with shrimp, mushrooms, lemongrass, galangal, and kaffir lime leaves.', price: 8.99, imageId: 'food-38' },
        ],
      },
    ],
  },
  {
    id: '11',
    name: 'The Vegan Spot',
    slug: 'the-vegan-spot',
    imageId: 'restaurant-11',
    cuisine: 'Vegan',
    rating: 4.9,
    reviews: 1500,
    deliveryTime: 20,
    deliveryFee: 2.99,
    categories: ['Vegan', 'Healthy', 'Salads'],
    menu: [
      {
        title: 'Bowls',
        items: [
          { id: '1101', name: 'Buddha Bowl', description: 'A colorful and nourishing bowl filled with roasted sweet potatoes, broccoli, quinoa, and chickpeas, all drizzled with a creamy tahini dressing.', price: 14.99, imageId: 'food-25' },
          { id: '1102', name: 'Spicy "Tuna" Bowl', description: 'Our signature plant-based "tuna" made from seasoned tomatoes, served over brown rice with avocado, cucumber, and a spicy sriracha aioli.', price: 15.99, imageId: 'food-39' },
        ],
      },
      {
        title: 'Burgers',
        items: [
          { id: '1103', name: 'Impossible Burger', description: 'A juicy, plant-based Impossible patty that tastes just like the real thing. Served with vegan cheese, lettuce, tomato, and our special sauce.', price: 16.99, imageId: 'food-40' },
        ],
      },
    ],
  },
  {
    id: '12',
    name: 'Steakhouse Supreme',
    slug: 'steakhouse-supreme',
    imageId: 'restaurant-12',
    cuisine: 'Steakhouse',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 40,
    deliveryFee: 5.00,
    categories: ['Steak', 'American', 'Fine Dining'],
    menu: [
      {
        title: 'Steaks',
        items: [
          { id: '1201', name: 'Filet Mignon (8oz)', description: 'Our most tender cut of beef, aged for 28 days and cooked to your desired temperature. Served with a red wine reduction sauce.', price: 45.99, imageId: 'food-41' },
          { id: '1202', name: 'Ribeye (12oz)', description: 'A well-marbled and incredibly flavorful cut, known for its rich taste. Grilled over an open flame for a perfect char.', price: 39.99, imageId: 'food-42' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '1203', name: 'Creamed Spinach', description: 'A rich and creamy steakhouse classic. Fresh spinach cooked with garlic, cream, and a hint of nutmeg.', price: 9.99, imageId: 'food-43' },
        ],
      },
    ],
  },
  {
    id: '13',
    name: 'Mediterranean Bites',
    slug: 'mediterranean-bites',
    imageId: 'restaurant-13',
    cuisine: 'Mediterranean',
    rating: 4.7,
    reviews: 850,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Mediterranean', 'Greek', 'Healthy'],
    menu: [
      {
        title: 'Plates',
        items: [
          { id: '1301', name: 'Chicken Shawarma Plate', description: 'Tender, marinated chicken, slow-roasted on a vertical spit, served with fluffy basmati rice, a side salad, and garlic sauce.', price: 17.99, imageId: 'food-1' },
          { id: '1302', name: 'Falafel Plate', description: 'Five crispy, golden-brown falafel balls made from ground chickpeas and herbs. Served with hummus, salad, and warm pita bread.', price: 14.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '14',
    name: 'Breakfast Club',
    slug: 'breakfast-club',
    imageId: 'restaurant-14',
    cuisine: 'Breakfast',
    rating: 4.6,
    reviews: 1100,
    deliveryTime: 22,
    deliveryFee: 2.50,
    categories: ['Breakfast', 'American', 'Cafe'],
    menu: [
      {
        title: 'Classics',
        items: [
          { id: '1401', name: 'Pancakes Stack', description: 'A fluffy stack of three buttermilk pancakes, served with a pad of butter and warm maple syrup.', price: 12.99, imageId: 'food-3' },
          { id: '1402', name: 'Eggs Benedict', description: 'Two perfectly poached eggs and Canadian bacon on a toasted English muffin, all smothered in a rich, creamy hollandaise sauce.', price: 15.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '15',
    name: 'The Ramen Shop',
    slug: 'the-ramen-shop',
    imageId: 'restaurant-15',
    cuisine: 'Japanese',
    rating: 4.8,
    reviews: 1300,
    deliveryTime: 33,
    deliveryFee: 3.80,
    categories: ['Japanese', 'Ramen', 'Noodles'],
    menu: [
      {
        title: 'Ramen',
        items: [
          { id: '1501', name: 'Tonkotsu Ramen', description: 'A rich, creamy pork broth ramen, topped with tender chashu pork, a soft-boiled egg, bamboo shoots, and scallions.', price: 16.99, imageId: 'food-5' },
          { id: '1502', name: 'Miso Ramen', description: 'A savory soybean paste broth with wavy noodles, topped with corn, seaweed, bean sprouts, and your choice of chicken or tofu.', price: 15.99, imageId: 'food-6' },
        ],
      },
    ],
  },
  {
    id: '16',
    name: 'BBQ Central',
    slug: 'bbq-central',
    imageId: 'restaurant-16',
    cuisine: 'BBQ',
    rating: 4.5,
    reviews: 950,
    deliveryTime: 45,
    deliveryFee: 4.50,
    categories: ['BBQ', 'American', 'Grill'],
    menu: [
      {
        title: 'Meats',
        items: [
          { id: '1601', name: 'Pulled Pork Sandwich', description: 'Our signature slow-smoked pulled pork, piled high on a toasted brioche bun and drizzled with our tangy BBQ sauce.', price: 14.99, imageId: 'food-7' },
          { id: '1602', name: 'Beef Brisket', description: 'Incredibly tender, melt-in-your-mouth beef brisket, smoked for 12 hours. Sold by the pound, perfect for sharing.', price: 28.99, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: '17',
    name: 'The Sweet Spot',
    slug: 'the-sweet-spot',
    imageId: 'restaurant-17',
    cuisine: 'Desserts',
    rating: 4.9,
    reviews: 2100,
    deliveryTime: 18,
    deliveryFee: 2.00,
    categories: ['Desserts', 'Bakery', 'Sweets'],
    menu: [
      {
        title: 'Cakes',
        items: [
          { id: '1701', name: 'Chocolate Lava Cake', description: 'A decadent, individual-sized warm chocolate cake with a gooey, molten chocolate center. Served with a dusting of powdered sugar.', price: 8.99, imageId: 'food-9' },
          { id: '1702', name: 'New York Cheesecake', description: 'A classic, rich, and creamy New York-style cheesecake with a graham cracker crust. A timeless dessert.', price: 7.99, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: '18',
    name: 'Healthy Habits',
    slug: 'healthy-habits',
    imageId: 'restaurant-18',
    cuisine: 'Healthy',
    rating: 4.7,
    reviews: 780,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Healthy', 'Smoothies', 'Bowls'],
    menu: [
      {
        title: 'Smoothies',
        items: [
          { id: '1801', name: 'Green Detox Smoothie', description: 'A refreshing blend of fresh spinach, kale, crisp apple, banana, and a splash of coconut water.', price: 9.99, imageId: 'food-11' },
          { id: '1802', name: 'Berry Blast Smoothie', description: 'A delicious mix of strawberries, blueberries, raspberries, and Greek yogurt, with a touch of honey for sweetness.', price: 9.99, imageId: 'food-12' },
        ],
      },
    ],
  },
   {
    id: '19',
    name: 'Cluck-a-Doodle',
    slug: 'cluck-a-doodle',
    imageId: 'restaurant-19',
    cuisine: 'Chicken',
    rating: 4.6,
    reviews: 1300,
    deliveryTime: 25,
    deliveryFee: 3.50,
    categories: ['Chicken', 'Fast Food', 'American'],
    menu: [
      {
        title: 'Fried Chicken',
        items: [
          { id: '1901', name: '3-Piece Fried Chicken', description: 'Three pieces of our signature crispy and juicy fried chicken, hand-breaded and cooked to golden perfection.', price: 12.99, imageId: 'food-44' },
          { id: '1902', name: 'Spicy Chicken Sandwich', description: 'A fiery, crispy chicken breast fillet on a toasted brioche bun with crunchy pickles and our secret spicy sauce.', price: 9.99, imageId: 'food-45' },
        ],
      },
    ],
  },
  {
    id: '20',
    name: 'Boba Bliss',
    slug: 'boba-bliss',
    imageId: 'restaurant-20',
    cuisine: 'Bubble Tea',
    rating: 4.9,
    reviews: 2500,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bubble Tea', 'Drinks', 'Desserts'],
    menu: [
      {
        title: 'Milk Teas',
        items: [
          { id: '2001', name: 'Classic Milk Tea', description: 'Our signature rich black tea blend, shaken with creamy milk and served with chewy tapioca pearls.', price: 5.50, imageId: 'food-46' },
          { id: '2002', name: 'Taro Milk Tea', description: 'A sweet and creamy milk tea with the distinct flavor of taro root, complete with delicious boba.', price: 6.00, imageId: 'food-47' },
        ],
      },
    ],
  },
  {
    id: '21',
    name: 'The Halal Guys',
    slug: 'the-halal-guys',
    imageId: 'restaurant-21',
    cuisine: 'Halal',
    rating: 4.7,
    reviews: 5000,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Halal', 'Mediterranean', 'Street Food', 'Fast Food'],
    menu: [
      {
        title: 'Platters',
        items: [
          { id: '2101', name: 'Chicken & Gyro Combo', description: 'The best of both worlds. A generous platter of our famous chicken and gyro meat served over seasoned rice with our legendary white sauce.', price: 14.99, imageId: 'food-48' },
          { id: '2102', name: 'Falafel Platter', description: 'Deliciously crispy falafel served over a bed of rice, with lettuce, tomato, and a drizzle of our famous white sauce.', price: 12.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '22',
    name: 'Sublime Sandwiches',
    slug: 'sublime-sandwiches',
    imageId: 'restaurant-22',
    cuisine: 'Sandwiches',
    rating: 4.5,
    reviews: 600,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Sandwiches', 'Deli', 'Lunch'],
    menu: [
      {
        title: 'Hot Sandwiches',
        items: [
          { id: '2201', name: 'Philly Cheesesteak', description: 'A hearty sandwich with thinly-sliced beef, melted provolone cheese, and grilled onions on a soft hoagie roll.', price: 13.99, imageId: 'food-49' },
          { id: '2202', name: 'Italian Meatball Sub', description: 'Hearty meatballs simmered in our house marinara sauce, topped with melted provolone cheese and served on a toasted sub roll.', price: 12.99, imageId: 'food-50' },
        ],
      },
    ],
  },
  {
    id: '23',
    name: 'Athens Grill',
    slug: 'athens-grill',
    imageId: 'restaurant-13',
    cuisine: 'Greek',
    rating: 4.8,
    reviews: 950,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Greek', 'Mediterranean', 'Healthy'],
    menu: [
      {
        title: 'Gyros',
        items: [
          { id: '2301', name: 'Lamb Gyro', description: 'Thinly sliced, seasoned lamb wrapped in a warm pita with fresh tomatoes, onions, and our creamy tzatziki sauce.', price: 11.99, imageId: 'food-1' },
          { id: '2302', name: 'Chicken Souvlaki Pita', description: 'Tender, marinated grilled chicken skewers wrapped in a fluffy pita with lettuce, tomatoes, and a dollop of tzatziki.', price: 10.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '24',
    name: 'Perfectly Pasta',
    slug: 'perfectly-pasta',
    imageId: 'restaurant-1',
    cuisine: 'Italian',
    rating: 4.6,
    reviews: 800,
    deliveryTime: 28,
    deliveryFee: 3.50,
    categories: ['Italian', 'Pasta', 'Noodle'],
    menu: [
      {
        title: 'Pasta',
        items: [
          { id: '2401', name: 'Fettuccine Alfredo', description: 'Classic fettuccine noodles tossed in a rich and creamy parmesan sauce, finished with a touch of black pepper.', price: 17.99, imageId: 'food-3' },
          { id: '2402', name: 'Pesto Gnocchi', description: 'Soft, pillowy potato gnocchi tossed in a vibrant basil pesto sauce and topped with shaved parmesan cheese.', price: 18.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '25',
    name: 'The Cake Box',
    slug: 'the-cake-box',
    imageId: 'restaurant-17',
    cuisine: 'Bakery',
    rating: 4.9,
    reviews: 1200,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Bakery', 'Desserts', 'Sweets'],
    menu: [
      {
        title: 'Cupcakes',
        items: [
          { id: '2501', name: 'Red Velvet Cupcake', description: 'A southern classic. Moist red velvet cake topped with a generous swirl of our signature cream cheese frosting.', price: 4.50, imageId: 'food-9' },
          { id: '2502', name: 'Chocolate Fudge Cupcake', description: 'A chocoholic\'s delight! A rich chocolate cupcake with a gooey fudge center, topped with chocolate buttercream.', price: 4.50, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: '26',
    name: 'Waffle House',
    slug: 'waffle-house',
    imageId: 'restaurant-23',
    cuisine: 'Breakfast',
    rating: 4.4,
    reviews: 2500,
    deliveryTime: 20,
    deliveryFee: 3.50,
    categories: ['Breakfast', 'Waffles', 'American'],
    menu: [
      {
        title: 'Waffles',
        items: [
          { id: '2601', name: 'Classic Belgian Waffle', description: 'A large, golden-brown Belgian waffle, light and crispy on the outside, fluffy on the inside. Served with whipped cream and fresh strawberries.', price: 10.99, imageId: 'food-51' },
          { id: '2602', name: 'Chocolate Chip Waffle', description: 'Our classic waffle loaded with melted chocolate chips and drizzled with chocolate syrup. A sweet start to your day.', price: 11.99, imageId: 'food-52' },
        ],
      },
    ],
  },
  {
    id: '27',
    name: 'Pancake Palace',
    slug: 'pancake-palace',
    imageId: 'restaurant-24',
    cuisine: 'Breakfast',
    rating: 4.5,
    reviews: 1900,
    deliveryTime: 22,
    deliveryFee: 3.00,
    categories: ['Breakfast', 'Pancakes', 'American'],
    menu: [
      {
        title: 'Pancakes',
        items: [
          { id: '2701', name: 'Buttermilk Pancake Stack', description: 'A tall stack of five of our famous, fluffy buttermilk pancakes. Served with butter and maple syrup.', price: 11.99, imageId: 'food-53' },
          { id: '2702', name: 'Blueberry Pancakes', description: 'Our classic pancakes filled with juicy, wild blueberries and dusted with powdered sugar.', price: 12.99, imageId: 'food-54' },
        ],
      },
    ],
  },
  {
    id: '28',
    name: 'The Muffin Man',
    slug: 'the-muffin-man',
    imageId: 'restaurant-25',
    cuisine: 'Bakery',
    rating: 4.7,
    reviews: 800,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bakery', 'Breakfast', 'Coffee'],
    menu: [
      {
        title: 'Muffins',
        items: [
          { id: '2801', name: 'Blueberry Muffin', description: 'A bakery classic. A moist and fluffy muffin bursting with sweet, juicy blueberries and a crumbly sugar topping.', price: 3.99, imageId: 'food-55' },
          { id: '2802', name: 'Chocolate Chip Muffin', description: 'A rich and decadent muffin packed with semi-sweet chocolate chips. Perfect for a morning treat or an afternoon snack.', price: 3.99, imageId: 'food-56' },
        ],
      },
    ],
  },
  {
    id: '29',
    name: 'Sunrise Eats',
    slug: 'sunrise-eats',
    imageId: 'restaurant-26',
    cuisine: 'Breakfast',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Breakfast', 'Brunch', 'American'],
    menu: [
      {
        title: 'Breakfast Plates',
        items: [
          { id: '2901', name: 'The Grand Slam', description: 'The ultimate breakfast feast! Two fluffy pancakes, two eggs your way, two strips of bacon, and two sausage links.', price: 16.99, imageId: 'food-57' },
          { id: '2902', name: 'Avocado Toast', description: 'Thick-cut sourdough toast topped with fresh, smashed avocado, a perfectly poached egg, and a sprinkle of red pepper flakes.', price: 13.99, imageId: 'food-58' },
        ],
      },
    ],
  },
  {
    id: '30',
    name: 'Burger Barn',
    slug: 'burger-barn',
    imageId: 'restaurant-27',
    cuisine: 'Burgers',
    rating: 4.3,
    reviews: 750,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Burgers', 'American', 'Fast Food'],
    menu: [{ title: 'Burgers', items: [{ id: '3001', name: 'The Farmhand Burger', description: 'A hearty burger with two all-beef patties, sharp cheddar cheese, crispy bacon, and a sunny-side-up fried egg on a brioche bun.', price: 15.99, imageId: 'food-9' }] }],
  },
  {
    id: '31',
    name: 'The Patty Shack',
    slug: 'the-patty-shack',
    imageId: 'restaurant-28',
    cuisine: 'Burgers',
    rating: 4.6,
    reviews: 900,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Burgers', 'American', 'Fast Food'],
    menu: [{ title: 'Burgers', items: [{ id: '3101', name: 'Shack Special', description: 'Our signature single patty burger with our secret shack sauce, crisp lettuce, tomato, and pickles on a toasted potato bun.', price: 10.99, imageId: 'food-10' }] }],
  },
  {
    id: '32',
    name: 'Grill Marks',
    slug: 'grill-marks',
    imageId: 'restaurant-29',
    cuisine: 'Burgers',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Burgers', 'American', 'Grill'],
    menu: [{ title: 'Burgers', items: [{ id: '3201', name: 'The Griller', description: 'A perfectly flame-grilled patty topped with smoked gouda cheese, sweet and savory onion jam, and arugula on a pretzel bun.', price: 13.99, imageId: 'food-9' }] }],
  },
  {
    id: '33',
    name: 'Burgerology',
    slug: 'burgerology',
    imageId: 'restaurant-30',
    cuisine: 'Burgers',
    rating: 4.8,
    reviews: 1500,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Burgers', 'American', 'Gourmet'],
    menu: [{ title: 'Burgers', items: [{ id: '3301', name: 'The Einstein', description: 'A burger of pure genius. A premium Wagyu beef patty, black truffle aioli, crispy shallots, and fresh arugula on a brioche bun.', price: 18.99, imageId: 'food-10' }] }],
  },
  {
    id: '34',
    name: 'Espresso Yourself',
    slug: 'espresso-yourself',
    imageId: 'restaurant-31',
    cuisine: 'Coffee',
    rating: 4.7,
    reviews: 980,
    deliveryTime: 12,
    deliveryFee: 1.80,
    categories: ['Coffee', 'Cafe', 'Bakery'],
    menu: [{ title: 'Coffee', items: [{ id: '3401', name: 'Caramel Macchiato', description: 'Freshly steamed milk with vanilla-flavored syrup marked with espresso and topped with a caramel drizzle for an oh-so-sweet finish.', price: 5.25, imageId: 'food-33' }] }],
  },
  {
    id: '35',
    name: 'The Grind',
    slug: 'the-grind',
    imageId: 'restaurant-32',
    cuisine: 'Coffee',
    rating: 4.6,
    reviews: 850,
    deliveryTime: 10,
    deliveryFee: 1.50,
    categories: ['Coffee', 'Cafe'],
    menu: [{ title: 'Coffee', items: [{ id: '3501', name: 'Cold Brew', description: 'Our signature coffee beans, slow-steeped in cool water for 20 hours for a smooth, less acidic, and highly caffeinated coffee experience.', price: 4.75, imageId: 'food-34' }] }],
  },
  {
    id: '36',
    name: 'Mocha Motion',
    slug: 'mocha-motion',
    imageId: 'restaurant-33',
    cuisine: 'Coffee',
    rating: 4.5,
    reviews: 700,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Coffee', 'Cafe', 'Desserts'],
    menu: [{ title: 'Coffee', items: [{ id: '3601', name: 'Iced Mocha', description: 'A delightful combination of rich espresso, bittersweet mocha sauce, and milk served over ice. Topped with whipped cream.', price: 5.50, imageId: 'food-33' }] }],
  },
  {
    id: '37',
    name: 'Slice of Heaven',
    slug: 'slice-of-heaven',
    imageId: 'restaurant-34',
    cuisine: 'Pizza',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Pizza', 'Italian'],
    menu: [{ title: 'Pizzas', items: [{ id: '3701', name: 'Meat Lover\'s Pizza', description: 'A carnivore\'s dream. Loaded with pepperoni, Italian sausage, crispy bacon, and savory ham on our classic crust.', price: 19.99, imageId: 'food-30' }] }],
  },
  {
    id: '38',
    name: 'The Pizza Peel',
    slug: 'the-pizza-peel',
    imageId: 'restaurant-35',
    cuisine: 'Pizza',
    rating: 4.7,
    reviews: 1200,
    deliveryTime: 28,
    deliveryFee: 2.90,
    categories: ['Pizza', 'Italian', 'Gourmet'],
    menu: [{ title: 'Pizzas', items: [{ id: '3801', name: 'Prosciutto & Arugula Pizza', description: 'A sophisticated white pizza with fresh mozzarella, topped with salty prosciutto, peppery arugula, shaved parmesan, and a sweet balsamic glaze.', price: 21.99, imageId: 'food-31' }] }],
  },
  {
    id: '39',
    name: 'Dough Boys',
    slug: 'dough-boys',
    imageId: 'restaurant-36',
    cuisine: 'Pizza',
    rating: 4.5,
    reviews: 880,
    deliveryTime: 25,
    deliveryFee: 2.50,
    categories: ['Pizza', 'Fast Food'],
    menu: [{ title: 'Pizzas', items: [{ id: '3901', name: 'BBQ Chicken Pizza', description: 'A tangy and sweet pizza with a BBQ sauce base, grilled chicken, red onions, and fresh cilantro.', price: 18.99, imageId: 'food-30' }] }],
  },
  {
    id: '40',
    name: 'Zaiqa Halal',
    slug: 'zaiqa-halal',
    imageId: 'restaurant-37',
    cuisine: 'Halal',
    rating: 4.8,
    reviews: 1300,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Halal', 'Indian', 'Pakistani'],
    menu: [{ title: 'Grill', items: [{ id: '4001', name: 'Chicken Biryani', description: 'A classic South Asian dish. Long-grain basmati rice cooked with tender chicken, exotic spices, and fragrant saffron.', price: 15.99, imageId: 'food-17' }] }],
  },
  {
    id: '41',
    name: 'Kabab Korner',
    slug: 'kabab-korner',
    imageId: 'restaurant-38',
    cuisine: 'Halal',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 28,
    deliveryFee: 3.00,
    categories: ['Halal', 'Middle Eastern', 'Grill'],
    menu: [{ title: 'Grill', items: [{ id: '4101', name: 'Beef Kabab Platter', description: 'Two skewers of seasoned and grilled ground beef kababs, served with basmati rice, grilled vegetables, and a side of yogurt sauce.', price: 18.99, imageId: 'food-48' }] }],
  },
  {
    id: '42',
    name: 'Royal Halal',
    slug: 'royal-halal',
    imageId: 'restaurant-39',
    cuisine: 'Halal',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 32,
    deliveryFee: 3.80,
    categories: ['Halal', 'Indian'],
    menu: [{ title: 'Curries', items: [{ id: '4201', name: 'Lamb Karahi', description: 'Tender pieces of lamb cooked in a traditional karahi (wok) with tomatoes, ginger, garlic, and a blend of spices.', price: 17.99, imageId: 'food-18' }] }],
  },
  {
    id: '43',
    name: 'NYC Street Cart',
    slug: 'nyc-street-cart',
    imageId: 'restaurant-21',
    cuisine: 'Halal',
    rating: 4.9,
    reviews: 3500,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Halal', 'Street Food', 'Fast Food'],
    menu: [{ title: 'Platters', items: [{ id: '4301', name: 'Lamb over Rice', description: 'The iconic New York street food. Tender lamb served over seasoned rice with lettuce, tomato, and our legendary white sauce.', price: 13.99, imageId: 'food-48' }] }],
  },
  {
    id: '44',
    name: 'The Fryer',
    slug: 'the-fryer',
    imageId: 'restaurant-40',
    cuisine: 'Chicken',
    rating: 4.5,
    reviews: 980,
    deliveryTime: 20,
    deliveryFee: 2.80,
    categories: ['Chicken', 'Fast Food'],
    menu: [{ title: 'Chicken', items: [{ id: '4401', name: 'Chicken Tenders Basket', description: 'Crispy, all-white meat chicken tenders served with a generous portion of our signature fries and your choice of dipping sauce.', price: 11.99, imageId: 'food-44' }] }],
  },
  {
    id: '45',
    name: 'Wing World',
    slug: 'wing-world',
    imageId: 'restaurant-41',
    cuisine: 'Chicken',
    rating: 4.7,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Chicken', 'Wings', 'American'],
    menu: [{ title: 'Wings', items: [{ id: '4501', name: '10pc Buffalo Wings', description: 'Ten crispy chicken wings tossed in our classic, spicy buffalo sauce. Served with a side of creamy ranch or blue cheese dressing.', price: 14.99, imageId: 'food-45' }] }],
  },
  {
    id: '46',
    name: 'The Coop',
    slug: 'the-coop',
    imageId: 'restaurant-42',
    cuisine: 'Chicken',
    rating: 4.6,
    reviews: 1150,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Chicken', 'Sandwiches', 'American'],
    menu: [{ title: 'Sandwiches', items: [{ id: '4601', name: 'Grilled Chicken Club', description: 'A triple-decker sandwich with a tender grilled chicken breast, crispy bacon, lettuce, tomato, and mayo on toasted bread.', price: 13.99, imageId: 'food-49' }] }],
  },
  {
    id: '47',
    name: 'Fowl Play',
    slug: 'fowl-play',
    imageId: 'restaurant-19',
    cuisine: 'Chicken',
    rating: 4.8,
    reviews: 1600,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Chicken', 'Gourmet', 'American'],
    menu: [{ title: 'Mains', items: [{ id: '4701', name: 'Roasted Half Chicken', description: 'A juicy, herb-roasted half chicken, cooked to perfection with crispy skin. Served with a side of roasted root vegetables.', price: 19.99, imageId: 'food-44' }] }],
  },
  {
    id: '48',
    name: 'Teatime',
    slug: 'teatime',
    imageId: 'restaurant-43',
    cuisine: 'Bubble Tea',
    rating: 4.8,
    reviews: 1900,
    deliveryTime: 12,
    deliveryFee: 1.90,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Fruit Teas', items: [{ id: '4801', name: 'Mango Green Tea', description: 'A refreshing and fruity green tea infused with sweet mango puree and served with chewy popping boba.', price: 6.25, imageId: 'food-46' }] }],
  },
  {
    id: '49',
    name: 'The Boba Spot',
    slug: 'the-boba-spot',
    imageId: 'restaurant-44',
    cuisine: 'Bubble Tea',
    rating: 4.7,
    reviews: 1500,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Specials', items: [{ id: '4901', name: 'Brown Sugar Boba', description: 'A decadent treat. Chewy tapioca pearls simmered in a rich brown sugar syrup, served with fresh, creamy milk.', price: 6.50, imageId: 'food-47' }] }],
  },
  {
    id: '50',
    name: 'Pearl Passion',
    slug: 'pearl-passion',
    imageId: 'restaurant-20',
    cuisine: 'Bubble Tea',
    rating: 4.6,
    reviews: 1200,
    deliveryTime: 18,
    deliveryFee: 2.20,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Milk Teas', items: [{ id: '5001', name: 'Oolong Milk Tea', description: 'A deeply aromatic and roasted oolong tea, balanced with creamy milk for a smooth and sophisticated flavor.', price: 5.75, imageId: 'food-46' }] }],
  },
   {
    id: '51',
    name: 'Chatterbox Cafe',
    slug: 'chatterbox-cafe',
    imageId: 'restaurant-43',
    cuisine: 'Bubble Tea',
    rating: 4.8,
    reviews: 1900,
    deliveryTime: 12,
    deliveryFee: 1.90,
    categories: ['Bubble Tea', 'Coffee', 'Desserts'],
    menu: [{ title: 'Fruit Teas', items: [{ id: '5101', name: 'Peach Oolong Tea', description: 'A light and refreshing oolong tea infused with sweet peach flavor and containing real fruit bits.', price: 6.00, imageId: 'food-47' }] }],
  },
  {
    id: '52',
    name: 'Indian Tadka',
    slug: 'indian-tadka',
    imageId: 'restaurant-5',
    cuisine: 'Indian',
    rating: 4.7,
    reviews: 1800,
    deliveryTime: 38,
    deliveryFee: 4.20,
    categories: ['Indian', 'Curry'],
    menu: [{ title: 'Vegetarian', items: [{ id: '5201', name: 'Aloo Gobi', description: 'A classic vegetarian dish from North India. Tender cauliflower and potatoes cooked with onions, tomatoes, and a blend of Indian spices.', price: 14.99, imageId: 'food-18' }] }],
  },
  {
    id: '53',
    name: 'Saffron Sun',
    slug: 'saffron-sun',
    imageId: 'restaurant-37',
    cuisine: 'Indian',
    rating: 4.9,
    reviews: 2200,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Indian', 'Fine Dining'],
    menu: [{ title: 'Mains', items: [{ id: '5301', name: 'Rogan Josh', description: 'A fragrant and aromatic lamb curry from the Kashmir region. Tender lamb pieces are braised in a gravy flavored with aromatic spices.', price: 19.99, imageId: 'food-17' }] }],
  },
  {
    id: '54',
    name: 'Mumbai Street Food',
    slug: 'mumbai-street-food',
    imageId: 'restaurant-39',
    cuisine: 'Indian',
    rating: 4.6,
    reviews: 1400,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Indian', 'Street Food'],
    menu: [{ title: 'Snacks', items: [{ id: '5401', name: 'Pav Bhaji', description: 'A popular Mumbai street food. A spicy mash of mixed vegetables, served with soft, buttered bread rolls (pav).', price: 12.99, imageId: 'food-18' }] }],
  },
   {
    id: '55',
    name: 'Delhi Darbar',
    slug: 'delhi-darbar',
    imageId: 'restaurant-38',
    cuisine: 'Indian',
    rating: 4.8,
    reviews: 2500,
    deliveryTime: 40,
    deliveryFee: 4.50,
    categories: ['Indian', 'Mughlai', 'Fine Dining'],
    menu: [{ title: 'Tandoor', items: [{ id: '5501', name: 'Tandoori Chicken', description: 'A world-famous dish. Chicken marinated in yogurt and a special blend of spices, then cooked to smoky perfection in a traditional tandoor oven.', price: 18.99, imageId: 'food-17' }] }],
  },
  {
    id: '56',
    name: 'Sugar Rush',
    slug: 'sugar-rush',
    imageId: 'restaurant-45',
    cuisine: 'Desserts',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 15,
    deliveryFee: 2.20,
    categories: ['Desserts', 'Sweets'],
    menu: [{ title: 'Ice Cream', items: [{ id: '5601', name: 'Double Scoop Sundae', description: 'Build your own dream sundae! Choose any two of our premium ice cream flavors, and we\'ll top it with whipped cream, chocolate sauce, and a cherry.', price: 9.99, imageId: 'food-9' }] }],
  },
  {
    id: '57',
    name: 'Cookie Crumb',
    slug: 'cookie-crumb',
    imageId: 'restaurant-46',
    cuisine: 'Desserts',
    rating: 4.9,
    reviews: 2200,
    deliveryTime: 12,
    deliveryFee: 1.80,
    categories: ['Desserts', 'Cookies', 'Bakery'],
    menu: [{ title: 'Cookies', items: [{ id: '5701', name: 'Half Dozen Assorted Cookies', description: 'Can\'t decide? Get a mix of our six best-selling, freshly baked cookies, including Chocolate Chip, Oatmeal Raisin, and Snickerdoodle.', price: 15.00, imageId: 'food-10' }] }],
  },
  {
    id: '58',
    name: 'El Jefe Taqueria',
    slug: 'el-jefe-taqueria',
    imageId: 'restaurant-47',
    cuisine: 'Mexican',
    rating: 4.8,
    reviews: 1600,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Mexican', 'Tacos'],
    menu: [{ title: 'Tacos', items: [{ id: '5801', name: 'Baja Fish Tacos', description: 'A taste of Baja California. Crispy, beer-battered fish fillets in warm tortillas, topped with a crunchy cabbage slaw and a smoky chipotle aioli.', price: 13.99, imageId: 'food-13' }] }],
  },
  {
    id: '59',
    name: 'La Fiesta',
    slug: 'la-fiesta',
    imageId: 'restaurant-48',
    cuisine: 'Mexican',
    rating: 4.7,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Mexican', 'Enchiladas', 'Margaritas'],
    menu: [{ title: 'Entrees', items: [{ id: '5901', name: 'Chicken Enchiladas', description: 'Tender shredded chicken wrapped in corn tortillas, covered in a tangy green tomatillo sauce and melted cheese. Served with rice and beans.', price: 17.99, imageId: 'food-14' }] }],
  },
  {
    id: '60',
    name: 'Guac & Roll',
    slug: 'guac-and-roll',
    imageId: 'restaurant-49',
    cuisine: 'Mexican',
    rating: 4.6,
    reviews: 1100,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Mexican', 'Burritos', 'Bowls'],
    menu: [{ title: 'Bowls', items: [{ id: '6001', name: 'Burrito Bowl', description: 'All the goodness of a burrito, without the tortilla. Your choice of protein, rice, beans, and toppings served in a convenient bowl.', price: 14.99, imageId: 'food-15' }] }],
  },
  {
    id: '61',
    name: 'Cantina Laredo',
    slug: 'cantina-laredo',
    imageId: 'restaurant-4',
    cuisine: 'Mexican',
    rating: 4.5,
    reviews: 950,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Mexican', 'Fajitas', 'Tex-Mex'],
    menu: [{ title: 'Fajitas', items: [{ id: '6101', name: 'Sizzling Steak Fajitas', description: 'A show-stopping dish. Marinated steak, grilled with onions and peppers, served sizzling with warm tortillas and all the classic sides.', price: 22.99, imageId: 'food-16' }] }],
  },
  {
    id: '62',
    name: 'Opa! Greek Taverna',
    slug: 'opa-greek-taverna',
    imageId: 'restaurant-50',
    cuisine: 'Greek',
    rating: 4.9,
    reviews: 1800,
    deliveryTime: 32,
    deliveryFee: 3.80,
    categories: ['Greek', 'Mediterranean'],
    menu: [{ title: 'Appetizers', items: [{ id: '6201', name: 'Saganaki (Flaming Cheese)', description: 'A theatrical and delicious appetizer. Pan-fried Greek cheese, flambéed at your table with brandy and extinguished with a squeeze of lemon.', price: 12.99, imageId: 'food-1' }] }],
  },
  {
    id: '63',
    name: 'The Olive Tree',
    slug: 'the-olive-tree',
    imageId: 'restaurant-51',
    cuisine: 'Greek',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Greek', 'Mediterranean', 'Healthy'],
    menu: [{ title: 'Mains', items: [{ id: '6301', name: 'Lamb Chops', description: 'Four perfectly grilled and seasoned lamb chops, served with roasted lemon potatoes and a side of tzatziki sauce.', price: 25.99, imageId: 'food-2' }] }],
  },
  {
    id: '64',
    name: 'Zeus\'s Table',
    slug: 'zeuss-table',
    imageId: 'restaurant-13',
    cuisine: 'Greek',
    rating: 4.8,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Greek', 'Mediterranean', 'Seafood'],
    menu: [{ title: 'Seafood', items: [{ id: '6401', name: 'Grilled Octopus', description: 'Tender, chargrilled octopus marinated in olive oil, lemon, and Greek oregano. A true taste of the Aegean.', price: 21.99, imageId: 'food-1' }] }],
  },
  {
    id: '65',
    name: 'The Sub Stop',
    slug: 'the-sub-stop',
    imageId: 'restaurant-52',
    cuisine: 'Sandwiches',
    rating: 4.6,
    reviews: 850,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Sandwiches', 'Deli', 'Fast Food'],
    menu: [{ title: 'Cold Subs', items: [{ id: '6501', name: 'Turkey Club', description: 'A classic triple-decker sandwich with sliced turkey breast, crispy bacon, lettuce, tomato, and mayo on your choice of bread.', price: 11.99, imageId: 'food-49' }] }],
  },
  {
    id: '66',
    name: 'Dagwood\'s Deli',
    slug: 'dagwoods-deli',
    imageId: 'restaurant-53',
    cuisine: 'Sandwiches',
    rating: 4.7,
    reviews: 950,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Sandwiches', 'Deli'],
    menu: [{ title: 'Specialty', items: [{ id: '6601', name: 'The Reuben', description: 'A deli icon. Corned beef, Swiss cheese, sauerkraut, and Russian dressing grilled between slices of rye bread.', price: 14.99, imageId: 'food-50' }] }],
  },
  {
    id: '67',
    name: 'Melt Factory',
    slug: 'melt-factory',
    imageId: 'restaurant-54',
    cuisine: 'Sandwiches',
    rating: 4.8,
    reviews: 1200,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Sandwiches', 'Grilled Cheese', 'Comfort Food'],
    menu: [{ title: 'Grilled Cheese', items: [{ id: '6701', name: 'The Classic Melt', description: 'The ultimate comfort food. A perfect blend of sharp cheddar and provolone cheeses melted between two thick slices of buttery sourdough.', price: 9.99, imageId: 'food-49' }] }],
  },
  {
    id: '68',
    name: 'Panini Press',
    slug: 'panini-press',
    imageId: 'restaurant-22',
    cuisine: 'Sandwiches',
    rating: 4.7,
    reviews: 1050,
    deliveryTime: 18,
    deliveryFee: 2.60,
    categories: ['Sandwiches', 'Italian', 'Cafe'],
    menu: [{ title: 'Paninis', items: [{ id: '6801', name: 'Caprese Panini', description: 'A taste of Italy. Fresh mozzarella, ripe tomatoes, basil, and a drizzle of balsamic glaze, all pressed and grilled to perfection.', price: 12.99, imageId: 'food-50' }] }],
  },
  {
    id: '69',
    name: 'Pho King',
    slug: 'pho-king',
    imageId: 'restaurant-55',
    cuisine: 'Vietnamese',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Vietnamese', 'Noodles', 'Pho'],
    menu: [{ title: 'Pho', items: [{ id: '6901', name: 'Spicy Beef Pho', description: 'Our classic beef pho with a fiery kick of house-made chili oil. Not for the faint of heart!', price: 14.99, imageId: 'food-28' }] }],
  },
  {
    id: '70',
    name: 'Saigon Shack',
    slug: 'saigon-shack',
    imageId: 'restaurant-56',
    cuisine: 'Vietnamese',
    rating: 4.7,
    reviews: 1500,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Vietnamese', 'Banh Mi', 'Sandwiches'],
    menu: [{ title: 'Banh Mi', items: [{ id: '7001', name: 'Classic Banh Mi', description: 'A crispy baguette filled with savory grilled pork, rich pâté, pickled carrots and daikon, fresh cilantro, and jalapeños.', price: 10.99, imageId: 'food-49' }] }],
  },
  {
    id: '71',
    name: 'Hanoi House',
    slug: 'hanoi-house',
    imageId: 'restaurant-7',
    cuisine: 'Vietnamese',
    rating: 4.9,
    reviews: 2100,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Vietnamese', 'Fine Dining'],
    menu: [{ title: 'Mains', items: [{ id: '7101', name: 'Cha Ca La Vong', description: 'A famous Hanoi specialty. Grilled fish seasoned with dill and turmeric, served with vermicelli noodles, peanuts, and herbs.', price: 24.99, imageId: 'food-29' }] }],
  },
  {
    id: '72',
    name: 'Mekong Kitchen',
    slug: 'mekong-kitchen',
    imageId: 'restaurant-57',
    cuisine: 'Vietnamese',
    rating: 4.6,
    reviews: 1200,
    deliveryTime: 30,
    deliveryFee: 3.20,
    categories: ['Vietnamese', 'Noodles'],
    menu: [{ title: 'Noodle Bowls', items: [{ id: '7201', name: 'Bun Thit Nuong', description: 'A refreshing and flavorful bowl of cool vermicelli noodles, topped with chargrilled pork, fresh herbs, and a savory-sweet dipping sauce.', price: 15.99, imageId: 'food-28' }] }],
  }
];


export const allHomeFoods: Restaurant[] = [
  {
    id: 'hf1',
    name: "Maria's Kitchen",
    slug: 'marias-kitchen',
    imageId: 'food-1',
    cuisine: 'Homestyle Italian',
    rating: 4.9,
    reviews: 150,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Italian', 'Homemade', 'Pasta', 'Comfort Food'],
    menu: [
      {
        title: 'Family Recipes',
        items: [
          { id: 'hf101', name: 'Grandma\'s Lasagna', description: 'Layers of pasta, ricotta, and a rich, slow-simmered bolognese sauce. A comforting dish made with love, just like nonna used to make.', price: 18.00, imageId: 'food-3' },
          { id: 'hf102', name: 'Chicken Parmesan', description: 'Tender chicken breast, breaded and fried until golden, then smothered in homemade marinara sauce and melted mozzarella. Served with a side of spaghetti.', price: 17.50, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: 'hf2',
    name: 'Chen\'s Dumplings',
    slug: 'chens-dumplings',
    imageId: 'food-2',
    cuisine: 'Chinese',
    rating: 4.8,
    reviews: 210,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Chinese', 'Dumplings', 'Homemade'],
    menu: [
      {
        title: 'Dumplings',
        items: [
          { id: 'hf201', name: 'Pork & Chive Dumplings (12pcs)', description: 'Juicy, hand-wrapped dumplings filled with ground pork and fresh chives, pan-fried to a crispy perfection on the bottom and steamed on top.', price: 15.00, imageId: 'food-5' },
          { id: 'hf202', name: 'Veggie Dumplings (12pcs)', description: 'A delightful mix of shiitake mushrooms, crisp cabbage, and sweet carrots, wrapped in a delicate dough and steamed or pan-fried to your liking.', price: 14.00, imageId: 'food-6' },
        ],
      },
    ],
  },
  {
    id: 'hf3',
    name: "Javier's Tacos",
    slug: 'javiers-tacos',
    imageId: 'food-13',
    cuisine: 'Authentic Mexican',
    rating: 4.9,
    reviews: 300,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Mexican', 'Tacos', 'Homemade', 'Spicy'],
    menu: [
      {
        title: 'Street Tacos',
        items: [
          { id: 'hf301', name: 'Carne Asada Tacos (3)', description: 'Tender, marinated grilled steak chopped and served on warm corn tortillas with cilantro, onion, and a side of Javier\'s famous smoky salsa.', price: 12.00, imageId: 'food-13' },
          { id: 'hf302', name: 'Cochinita Pibil Tacos (3)', description: 'A Yucatan specialty. Slow-roasted pork marinated in citrus and achiote, creating a tender, flavorful filling, topped with pickled red onions.', price: 12.00, imageId: 'food-14' },
        ],
      },
    ],
  },
  {
    id: 'hf4',
    name: 'Healthy Home Bowls',
    slug: 'healthy-home-bowls',
    imageId: 'food-22',
    cuisine: 'Healthy Bowls',
    rating: 4.7,
    reviews: 95,
    deliveryTime: 15,
    deliveryFee: 4.00,
    categories: ['Healthy', 'Vegan', 'Bowls', 'Homemade'],
    menu: [
      {
        title: 'Nourish Bowls',
        items: [
          { id: 'hf401', name: 'Quinoa & Roasted Veggie Bowl', description: 'A vibrant bowl of fluffy quinoa, roasted seasonal vegetables like broccoli and sweet potatoes, and a creamy lemon-tahini dressing.', price: 16.00, imageId: 'food-22' },
          { id: 'hf402', name: 'Mediterranean Chicken Bowl', description: 'Grilled chicken breast, crumbled feta cheese, kalamata olives, cucumbers, and tomatoes over a bed of fluffy couscous with a light vinaigrette.', price: 17.00, imageId: 'food-23' },
        ],
      },
    ],
  },
  {
    id: 'hf5',
    name: "Priya's Indian Feast",
    slug: 'priyas-indian-feast',
    imageId: 'food-17',
    cuisine: 'Homestyle Indian',
    rating: 4.8,
    reviews: 180,
    deliveryTime: 35,
    deliveryFee: 3.75,
    categories: ['Indian', 'Curry', 'Homemade', 'Spicy'],
    menu: [
      {
        title: 'Curries',
        items: [
          { id: 'hf501', name: 'Homestyle Chicken Curry', description: 'A comforting and aromatic chicken curry with a medium spice level, made from a secret family recipe. Served with fluffy basmati rice.', price: 17.00, imageId: 'food-17' },
          { id: 'hf502', name: 'Dal Makhani', description: 'A rich and creamy dish of black lentils and kidney beans, slow-cooked for hours with butter, cream, and a blend of traditional spices.', price: 15.00, imageId: 'food-18' },
        ],
      },
    ],
  },
  {
    id: 'hf6',
    name: 'Brenda\'s BBQ',
    slug: 'brendas-bbq',
    imageId: 'food-7',
    cuisine: 'Southern BBQ',
    rating: 4.9,
    reviews: 250,
    deliveryTime: 45,
    deliveryFee: 5.00,
    categories: ['BBQ', 'American', 'Homemade', 'Comfort Food'],
    menu: [
      {
        title: 'BBQ Plates',
        items: [
          { id: 'hf601', name: 'Pulled Pork Plate', description: 'Slow-smoked for 10 hours until perfectly tender, served with a side of tangy homemade coleslaw and a slice of sweet cornbread.', price: 19.00, imageId: 'food-7' },
          { id: 'hf602', name: 'Smoked Ribs (Half Rack)', description: 'A half rack of our fall-off-the-bone tender pork ribs, glazed with our secret family recipe BBQ sauce. A true taste of the South.', price: 22.00, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: 'hf7',
    name: 'Mama Kim\'s Korean',
    slug: 'mama-kims-korean',
    imageId: 'food-24',
    cuisine: 'Korean',
    rating: 4.8,
    reviews: 190,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Korean', 'Homemade', 'Spicy'],
    menu: [
      {
        title: 'Main Dishes',
        items: [
          { id: 'hf701', name: 'Bibimbap', description: 'A classic Korean mixed rice bowl topped with an array of seasoned vegetables, savory beef, a sunny-side-up fried egg, and gochujang sauce.', price: 18.00, imageId: 'food-24' },
          { id: 'hf702', name: 'Kimchi Jjigae', description: 'A fiery and comforting kimchi stew with tender pork belly and soft tofu. A staple in every Korean home, perfect for a cold day.', price: 17.00, imageId: 'food-25' },
        ],
      },
    ],
  },
    {
    id: 'hf8',
    name: 'Sophie\'s Soups',
    slug: 'sophies-soups',
    imageId: 'food-38',
    cuisine: 'Soups & Stews',
    rating: 4.9,
    reviews: 120,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Soup', 'Comfort Food', 'Homemade', 'Healthy'],
    menu: [
      {
        title: 'Hearty Soups',
        items: [
          { id: 'hf801', name: 'Tomato Basil Soup', description: 'A creamy and rich tomato soup made from vine-ripened tomatoes and fresh basil, with a touch of cream. Served with a side of crusty bread for dipping.', price: 12.00, imageId: 'food-38' },
          { id: 'hf802', name: 'Chicken Noodle Soup', description: 'The ultimate comfort food. Made with a flavorful homemade chicken broth, tender chicken pieces, celery, carrots, and egg noodles.', price: 13.00, imageId: 'food-29' },
        ],
      },
    ],
  },
  {
    id: 'hf9',
    name: 'Baker Ben\'s Breads',
    slug: 'baker-bens-breads',
    imageId: 'food-19',
    cuisine: 'Artisan Bakery',
    rating: 4.9,
    reviews: 280,
    deliveryTime: 15,
    deliveryFee: 4.00,
    categories: ['Bakery', 'Bread', 'Homemade'],
    menu: [
      {
        title: 'Freshly Baked',
        items: [
          { id: 'hf901', name: 'Sourdough Loaf', description: 'A beautiful, naturally leavened sourdough loaf with a tangy flavor, a chewy crumb, and a satisfyingly crusty exterior. Baked fresh daily.', price: 9.00, imageId: 'food-19' },
          { id: 'hf902', name: 'Chocolate Babka', description: 'A sweet braided bread with a rich, gooey chocolate and cinnamon filling. Perfect for dessert or a special breakfast treat.', price: 14.00, imageId: 'food-27' },
        ],
      },
    ],
  },
  {
    id: 'hf10',
    name: 'Thai by Ton',
    slug: 'thai-by-ton',
    imageId: 'food-36',
    cuisine: 'Authentic Thai',
    rating: 4.8,
    reviews: 165,
    deliveryTime: 30,
    deliveryFee: 3.25,
    categories: ['Thai', 'Homemade', 'Spicy', 'Curry'],
    menu: [
      {
        title: 'Thai Favorites',
        items: [
          { id: 'hf1001', name: 'Green Curry with Chicken', description: 'An authentic and aromatic green curry made from Ton\'s homemade paste, with coconut milk, tender chicken, bamboo shoots, and Thai basil.', price: 17.50, imageId: 'food-37' },
          { id: 'hf1002', name: 'Drunken Noodles (Pad Kee Mao)', description: 'Spicy, stir-fried wide rice noodles with chicken, fresh basil, bell peppers, and onions in a savory sauce. A flavorful and fiery dish.', price: 16.50, imageId: 'food-36' },
        ],
      },
    ],
  },
  {
    id: 'hf11',
    name: 'Elena\'s Greek Kitchen',
    slug: 'elenas-greek-kitchen',
    imageId: 'food-21',
    cuisine: 'Greek',
    rating: 4.9,
    reviews: 195,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Greek', 'Mediterranean', 'Homemade'],
    menu: [
      {
        title: 'Greek Specialties',
        items: [
          { id: 'hf1101', name: 'Moussaka', description: 'A classic Greek casserole with layers of tender eggplant, seasoned ground meat, and a rich, creamy béchamel sauce, baked to perfection.', price: 19.00, imageId: 'food-21' },
          { id: 'hf1102', name: 'Spanakopita (Spinach Pie)', description: 'A savory pie made with flaky phyllo pastry, generously filled with spinach, feta cheese, onions, and fresh herbs. Sold by the slice.', price: 10.00, imageId: 'food-22' },
        ],
      },
    ],
  },
  {
    id: 'hf12',
    name: 'Frank\'s Famous Chili',
    slug: 'franks-famous-chili',
    imageId: 'food-24',
    cuisine: 'American Comfort',
    rating: 4.7,
    reviews: 88,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Comfort Food', 'American', 'Homemade', 'Soup'],
    menu: [
      {
        title: 'Chili Bowls',
        items: [
          { id: 'hf1201', name: 'Classic Beef Chili', description: 'Frank\'s award-winning recipe! A hearty and perfectly spiced beef chili with beans, served with a side of sour cream and shredded cheddar.', price: 15.00, imageId: 'food-24' },
          { id: 'hf1202', name: 'Vegetarian Three-Bean Chili', description: 'A flavorful and satisfying chili made with a mix of kidney, pinto, and black beans in a spiced tomato base, topped with green onions.', price: 14.00, imageId: 'food-25' },
        ],
      },
    ],
  },
   {
    id: 'hf13',
    name: 'Morning Sunshine Breakfast',
    slug: 'morning-sunshine-breakfast',
    imageId: 'food-57',
    cuisine: 'Breakfast',
    rating: 4.8,
    reviews: 110,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Breakfast', 'Homemade', 'American'],
    menu: [
      {
        title: 'Breakfast Classics',
        items: [
          { id: 'hf1301', name: 'Breakfast Burrito', description: 'A hearty burrito stuffed with scrambled eggs, savory sausage, potatoes, and cheese, wrapped in a warm flour tortilla.', price: 12.00, imageId: 'food-15' },
          { id: 'hf1302', name: 'French Toast', description: 'Thick slices of brioche bread soaked in a sweet custard batter, grilled to golden brown, and topped with powdered sugar and berries.', price: 14.00, imageId: 'food-54' },
        ],
      },
    ],
  },
  {
    id: 'hf14',
    name: 'Quick Bite Burgers',
    slug: 'quick-bite-burgers',
    imageId: 'food-9',
    cuisine: 'Burgers',
    rating: 4.6,
    reviews: 90,
    deliveryTime: 25,
    deliveryFee: 3.50,
    categories: ['Burgers', 'Fast Food', 'American', 'Homemade'],
    menu: [
      {
        title: 'Homemade Burgers',
        items: [
          { id: 'hf1401', name: 'The Backyard Burger', description: 'A simple, delicious beef patty, seasoned and grilled, served on a toasted bun with lettuce, tomato, and onion.', price: 13.00, imageId: 'food-9' },
          { id: 'hf1402', name: 'Mushroom Swiss Burger', description: 'A juicy beef patty topped with sautéed mushrooms and melted Swiss cheese on a brioche bun.', price: 14.50, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: 'hf15',
    name: 'Java at Home',
    slug: 'java-at-home',
    imageId: 'food-34',
    cuisine: 'Coffee',
    rating: 4.9,
    reviews: 150,
    deliveryTime: 10,
    deliveryFee: 2.00,
    categories: ['Coffee', 'Drinks', 'Homemade'],
    menu: [
      {
        title: 'Artisan Coffee',
        items: [
          { id: 'hf1501', name: 'Homemade Cold Brew', description: 'Small-batch cold brew coffee, steeped for 24 hours for a smooth, rich flavor. Served over ice.', price: 5.00, imageId: 'food-34' },
          { id: 'hf1502', name: 'Spiced Chai Latte', description: 'A warm and aromatic chai latte made with a blend of black tea, spices, and steamed milk.', price: 5.50, imageId: 'food-33' },
        ],
      },
    ],
  },
  {
    id: 'hf16',
    name: 'Pizza by the Pie',
    slug: 'pizza-by-the-pie',
    imageId: 'food-4',
    cuisine: 'Pizza',
    rating: 4.7,
    reviews: 120,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Pizza', 'Italian', 'Homemade'],
    menu: [
      {
        title: 'Handmade Pizzas',
        items: [
          { id: 'hf1601', name: 'Classic Pepperoni Pizza', description: 'A 12-inch pizza with a hand-tossed crust, zesty tomato sauce, mozzarella cheese, and plenty of pepperoni.', price: 16.00, imageId: 'food-30' },
          { id: 'hf1602', name: 'Four Cheese White Pizza', description: 'A creamy garlic sauce base topped with a blend of mozzarella, ricotta, parmesan, and provolone cheese.', price: 17.00, imageId: 'food-31' },
        ],
      },
    ],
  },
  {
    id: 'hf17',
    name: 'Halal Home Cooking',
    slug: 'halal-home-cooking',
    imageId: 'food-48',
    cuisine: 'Halal',
    rating: 4.8,
    reviews: 180,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Halal', 'Middle Eastern', 'Homemade'],
    menu: [
      {
        title: 'Halal Dishes',
        items: [
          { id: 'hf1701', name: 'Chicken Kabsa', description: 'A fragrant rice dish popular in the Gulf states, cooked with chicken, spices, and raisins.', price: 18.00, imageId: 'food-48' },
          { id: 'hf1702', name: 'Lamb Tagine', description: 'A slow-cooked Moroccan stew with tender lamb, apricots, and almonds in a savory, aromatic sauce.', price: 20.00, imageId: 'food-1' },
        ],
      },
    ],
  },
  {
    id: 'hf18',
    name: 'Crispy Cluckers',
    slug: 'crispy-cluckers',
    imageId: 'food-44',
    cuisine: 'Chicken',
    rating: 4.7,
    reviews: 130,
    deliveryTime: 30,
    deliveryFee: 3.25,
    categories: ['Chicken', 'American', 'Fast Food', 'Homemade'],
    menu: [
      {
        title: 'Fried Chicken',
        items: [
          { id: 'hf1801', name: 'Buttermilk Fried Chicken (4pcs)', description: 'Chicken pieces marinated in buttermilk, then double-dredged for an extra crispy coating.', price: 16.00, imageId: 'food-44' },
          { id: 'hf1802', name: 'Honey BBQ Wings (8pcs)', description: 'Crispy fried wings tossed in a sweet and tangy honey BBQ sauce.', price: 14.00, imageId: 'food-45' },
        ],
      },
    ],
  },
  {
    id: 'hf19',
    name: 'Boba Creations',
    slug: 'boba-creations',
    imageId: 'food-47',
    cuisine: 'Bubble Tea',
    rating: 4.9,
    reviews: 200,
    deliveryTime: 15,
    deliveryFee: 2.50,
    categories: ['Bubble Tea', 'Drinks', 'Desserts', 'Homemade'],
    menu: [
      {
        title: 'Handcrafted Boba',
        items: [
          { id: 'hf1901', name: 'Strawberry Matcha Latte', description: 'A beautiful and delicious layered drink with strawberry puree, creamy milk, and earthy matcha.', price: 6.50, imageId: 'food-46' },
          { id: 'hf1902', name: 'Passion Fruit Green Tea', description: 'A refreshing and tropical green tea with real passion fruit pulp and seeds, with your choice of popping boba or jelly.', price: 6.00, imageId: 'food-47' },
        ],
      },
    ],
  },
  {
    id: 'hf20',
    name: 'Sweet Endings',
    slug: 'sweet-endings',
    imageId: 'food-10',
    cuisine: 'Desserts',
    rating: 4.9,
    reviews: 170,
    deliveryTime: 20,
    deliveryFee: 2.75,
    categories: ['Desserts', 'Bakery', 'Homemade', 'Sweets'],
    menu: [
      {
        title: 'Homemade Sweets',
        items: [
          { id: 'hf2001', name: 'Fudgy Brownies', description: 'Rich, dense, and chewy chocolate brownies made with premium cocoa. Sold individually.', price: 4.00, imageId: 'food-9' },
          { id: 'hf2002', name: 'Apple Crumble', description: 'Warm baked apples with a cinnamon-spiced oat crumble topping. Served with a side of vanilla bean ice cream.', price: 8.00, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: 'hf21',
    name: 'The Sandwich Shop at Home',
    slug: 'the-sandwich-shop-at-home',
    imageId: 'food-50',
    cuisine: 'Sandwiches',
    rating: 4.7,
    reviews: 100,
    deliveryTime: 15,
    deliveryFee: 2.50,
    categories: ['Sandwiches', 'Deli', 'Lunch', 'Homemade'],
    menu: [
      {
        title: 'Artisan Sandwiches',
        items: [
          { id: 'hf2101', name: 'Roast Beef & Caramelized Onion', description: 'Thinly sliced roast beef, sweet caramelized onions, and sharp provolone on a toasted ciabatta roll with horseradish aioli.', price: 14.00, imageId: 'food-50' },
          { id: 'hf2102', name: 'Caprese Sandwich', description: 'Fresh mozzarella, ripe tomatoes, and basil pesto on a crusty baguette, drizzled with balsamic glaze.', price: 12.00, imageId: 'food-49' },
        ],
      },
    ],
  },
  {
    id: 'hf22',
    name: 'Noodle Nirvana',
    slug: 'noodle-nirvana',
    imageId: 'food-28',
    cuisine: 'Noodle Dishes',
    rating: 4.8,
    reviews: 140,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Noodle', 'Asian', 'Homemade', 'Comfort Food'],
    menu: [
      {
        title: 'Noodle Bowls',
        items: [
          { id: 'hf2201', name: 'Spicy Peanut Noodles', description: 'Chewy noodles tossed in a creamy, spicy peanut sauce with shredded chicken, carrots, and cilantro.', price: 16.00, imageId: 'food-28' },
          { id: 'hf2202', name: 'Garlic Shrimp Scampi', description: 'Linguine pasta with succulent shrimp in a garlic, white wine, and butter sauce with a hint of red pepper flakes.', price: 18.00, imageId: 'food-29' },
        ],
      },
    ],
  }
];

    

