import type { Restaurant } from './types';

export const allRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'The Golden Spoon',
    slug: 'the-golden-spoon',
    imageId: 'restaurant-1',
    cuisine: 'Italian',
    rating: 4.7,
    reviews: 1204,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Italian', 'Pasta', 'Pizza'],
    menu: [
      {
        title: 'Appetizers',
        items: [
          { id: '101', name: 'Bruschetta', description: 'Grilled bread with tomatoes, garlic, and basil.', price: 8.99, imageId: 'food-1' },
          { id: '102', name: 'Calamari Fritti', description: 'Fried squid with a zesty marinara sauce.', price: 12.99, imageId: 'food-2' },
        ],
      },
      {
        title: 'Main Courses',
        items: [
          { id: '103', name: 'Spaghetti Carbonara', description: 'Pasta with eggs, cheese, pancetta, and pepper.', price: 18.99, imageId: 'food-3' },
          { id: '104', name: 'Margherita Pizza', description: 'Classic pizza with tomatoes, mozzarella, and basil.', price: 15.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Sushi Palace',
    slug: 'sushi-palace',
    imageId: 'restaurant-2',
    cuisine: 'Japanese',
    rating: 4.9,
    reviews: 2345,
    deliveryTime: 30,
    deliveryFee: 4.50,
    categories: ['Japanese', 'Sushi', 'Asian'],
    menu: [
      {
        title: 'Sushi Rolls',
        items: [
          { id: '201', name: 'California Roll', description: 'Crab, avocado, and cucumber.', price: 10.99, imageId: 'food-5' },
          { id: '202', name: 'Spicy Tuna Roll', description: 'Tuna, spicy mayo, and cucumber.', price: 12.99, imageId: 'food-6' },
        ],
      },
      {
        title: 'Nigiri',
        items: [
          { id: '203', name: 'Salmon Nigiri', description: 'Fresh salmon over vinegared rice.', price: 6.99, imageId: 'food-7' },
          { id: '204', name: 'Tuna Nigiri', description: 'Premium tuna over vinegared rice.', price: 7.99, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Burger Bonanza',
    slug: 'burger-bonanza',
    imageId: 'restaurant-3',
    cuisine: 'American',
    rating: 4.5,
    reviews: 876,
    deliveryTime: 20,
    deliveryFee: 1.99,
    categories: ['American', 'Burgers', 'Fast Food'],
    menu: [
      {
        title: 'Burgers',
        items: [
          { id: '301', name: 'Classic Cheeseburger', description: 'Beef patty, cheese, lettuce, tomato, and onion.', price: 11.99, imageId: 'food-9' },
          { id: '302', name: 'Bacon Avocado Burger', description: 'Beef patty, bacon, avocado, and swiss cheese.', price: 14.99, imageId: 'food-10' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '303', name: 'French Fries', description: 'Crispy golden fries.', price: 4.99, imageId: 'food-11' },
          { id: '304', name: 'Onion Rings', description: 'Battered and fried onion rings.', price: 5.99, imageId: 'food-12' },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Taco Town',
    slug: 'taco-town',
    imageId: 'restaurant-4',
    cuisine: 'Mexican',
    rating: 4.6,
    reviews: 998,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Mexican', 'Tacos', 'Burritos'],
    menu: [
       {
        title: 'Tacos',
        items: [
          { id: '401', name: 'Carne Asada Taco', description: 'Grilled steak in a corn tortilla.', price: 3.99, imageId: 'food-13' },
          { id: '402', name: 'Al Pastor Taco', description: 'Marinated pork with pineapple.', price: 3.99, imageId: 'food-14' },
        ],
      },
      {
        title: 'Burritos',
        items: [
          { id: '403', name: 'Bean & Cheese Burrito', description: 'A classic simple burrito.', price: 8.99, imageId: 'food-15' },
          { id: '404', name: 'California Burrito', description: 'Carne asada, fries, cheese, and guacamole.', price: 12.99, imageId: 'food-16' },
        ],
      },
    ],
  },
  {
    id: '5',
    name: 'Curry House',
    slug: 'curry-house',
    imageId: 'restaurant-5',
    cuisine: 'Indian',
    rating: 4.8,
    reviews: 1543,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Indian', 'Curry', 'Vegetarian'],
    menu: [
       {
        title: 'Curries',
        items: [
          { id: '501', name: 'Chicken Tikka Masala', description: 'Creamy tomato-based curry with chicken.', price: 16.99, imageId: 'food-17' },
          { id: '502', name: 'Paneer Butter Masala', description: 'Indian cheese in a rich, creamy sauce.', price: 15.99, imageId: 'food-18' },
        ],
      },
      {
        title: 'Breads',
        items: [
          { id: '503', name: 'Garlic Naan', description: 'Soft flatbread with garlic and butter.', price: 3.99, imageId: 'food-19' },
          { id: '504', name: 'Roti', description: 'Whole wheat flatbread.', price: 2.99, imageId: 'food-20' },
        ],
      },
    ],
  },
  {
    id: '6',
    name: 'The Green Bowl',
    slug: 'the-green-bowl',
    imageId: 'restaurant-6',
    cuisine: 'Salads',
    rating: 4.9,
    reviews: 789,
    deliveryTime: 15,
    deliveryFee: 2.50,
    categories: ['Salads', 'Healthy', 'Vegan'],
    menu: [
       {
        title: 'Signature Salads',
        items: [
          { id: '601', name: 'Cobb Salad', description: 'Greens, chicken, bacon, egg, avocado, and blue cheese.', price: 14.99, imageId: 'food-21' },
          { id: '602', name: 'Quinoa & Avocado Power Bowl', description: 'Quinoa, avocado, chickpeas, and mixed greens.', price: 13.99, imageId: 'food-22' },
        ],
      },
      {
        title: 'Create Your Own',
        items: [
          { id: '603', name: 'Custom Salad', description: 'Choose your base, toppings, and dressing.', price: 15.99, imageId: 'food-23' },
        ],
      },
    ],
  },
  {
    id: '7',
    name: 'The Noodle Bar',
    slug: 'the-noodle-bar',
    imageId: 'restaurant-7',
    cuisine: 'Vietnamese',
    rating: 4.7,
    reviews: 890,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Vietnamese', 'Noodles', 'Pho'],
    menu: [
      {
        title: 'Pho',
        items: [
          { id: '701', name: 'Classic Beef Pho', description: 'Rich beef broth with rice noodles and sliced beef.', price: 13.99, imageId: 'food-28' },
          { id: '702', name: 'Chicken Pho', description: 'Savory chicken broth with shredded chicken.', price: 12.99, imageId: 'food-29' },
        ],
      },
      {
        title: 'Appetizers',
        items: [
          { id: '703', name: 'Fresh Spring Rolls', description: 'Shrimp, pork, and herbs wrapped in rice paper.', price: 7.99, imageId: 'food-26' },
        ],
      },
    ],
  },
  {
    id: '8',
    name: 'Pizza Planet',
    slug: 'pizza-planet',
    imageId: 'restaurant-8',
    cuisine: 'Pizza',
    rating: 4.4,
    reviews: 654,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Pizza', 'Italian', 'Fast Food'],
    menu: [
      {
        title: 'Specialty Pizzas',
        items: [
          { id: '801', name: 'Pepperoni Overload', description: 'Covered in classic pepperoni slices.', price: 17.99, imageId: 'food-30' },
          { id: '802', name: 'Veggie Supreme', description: 'Onions, peppers, olives, and mushrooms.', price: 16.99, imageId: 'food-31' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '803', name: 'Garlic Knots', description: 'Buttery garlic knots with marinara.', price: 6.99, imageId: 'food-32' },
        ],
      },
    ],
  },
  {
    id: '9',
    name: 'The Daily Grind',
    slug: 'the-daily-grind',
    imageId: 'restaurant-9',
    cuisine: 'Cafe',
    rating: 4.8,
    reviews: 1102,
    deliveryTime: 10,
    deliveryFee: 1.50,
    categories: ['Coffee', 'Cafe', 'Breakfast'],
    menu: [
      {
        title: 'Coffee & Tea',
        items: [
          { id: '901', name: 'Iced Latte', description: 'Espresso with chilled milk over ice.', price: 4.99, imageId: 'food-33' },
          { id: '902', name: 'Matcha Green Tea', description: 'Ceremonial grade matcha with steamed milk.', price: 5.49, imageId: 'food-34' },
        ],
      },
      {
        title: 'Pastries',
        items: [
          { id: '903', name: 'Croissant', description: 'Flaky, buttery, and freshly baked.', price: 3.50, imageId: 'food-35' },
        ],
      },
    ],
  },
  {
    id: '10',
    name: 'Bangkok Spice',
    slug: 'bangkok-spice',
    imageId: 'restaurant-10',
    cuisine: 'Thai',
    rating: 4.6,
    reviews: 932,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Thai', 'Curry', 'Asian'],
    menu: [
      {
        title: 'Main Dishes',
        items: [
          { id: '1001', name: 'Pad Thai', description: 'Stir-fried rice noodles with shrimp, tofu, and peanuts.', price: 15.99, imageId: 'food-36' },
          { id: '1002', name: 'Green Curry', description: 'Spicy green curry with chicken and bamboo shoots.', price: 16.99, imageId: 'food-37' },
        ],
      },
      {
        title: 'Appetizers',
        items: [
          { id: '1003', name: 'Tom Yum Soup', description: 'Hot and sour soup with shrimp and mushrooms.', price: 8.99, imageId: 'food-38' },
        ],
      },
    ],
  },
  {
    id: '11',
    name: 'The Vegan Spot',
    slug: 'the-vegan-spot',
    imageId: 'restaurant-11',
    cuisine: 'Vegan',
    rating: 4.9,
    reviews: 1500,
    deliveryTime: 20,
    deliveryFee: 2.99,
    categories: ['Vegan', 'Healthy', 'Salads'],
    menu: [
      {
        title: 'Bowls',
        items: [
          { id: '1101', name: 'Buddha Bowl', description: 'Roasted veggies, quinoa, and a tahini dressing.', price: 14.99, imageId: 'food-25' },
          { id: '1102', name: 'Spicy "Tuna" Bowl', description: 'Plant-based tuna with avocado and brown rice.', price: 15.99, imageId: 'food-39' },
        ],
      },
      {
        title: 'Burgers',
        items: [
          { id: '1103', name: 'Impossible Burger', description: 'A delicious plant-based patty with all the fixings.', price: 16.99, imageId: 'food-40' },
        ],
      },
    ],
  },
  {
    id: '12',
    name: 'Steakhouse Supreme',
    slug: 'steakhouse-supreme',
    imageId: 'restaurant-12',
    cuisine: 'Steakhouse',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 40,
    deliveryFee: 5.00,
    categories: ['Steak', 'American', 'Fine Dining'],
    menu: [
      {
        title: 'Steaks',
        items: [
          { id: '1201', name: 'Filet Mignon (8oz)', description: 'The most tender cut, cooked to perfection.', price: 45.99, imageId: 'food-41' },
          { id: '1202', name: 'Ribeye (12oz)', description: 'Well-marbled for peak flavor.', price: 39.99, imageId: 'food-42' },
        ],
      },
      {
        title: 'Sides',
        items: [
          { id: '1203', name: 'Creamed Spinach', description: 'A classic steakhouse side.', price: 9.99, imageId: 'food-43' },
        ],
      },
    ],
  },
  {
    id: '13',
    name: 'Mediterranean Bites',
    slug: 'mediterranean-bites',
    imageId: 'restaurant-13',
    cuisine: 'Mediterranean',
    rating: 4.7,
    reviews: 850,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Mediterranean', 'Greek', 'Healthy'],
    menu: [
      {
        title: 'Plates',
        items: [
          { id: '1301', name: 'Chicken Shawarma Plate', description: 'Marinated chicken, rice, and salad.', price: 17.99, imageId: 'food-1' },
          { id: '1302', name: 'Falafel Plate', description: 'Crispy falafel with tahini sauce.', price: 14.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '14',
    name: 'Breakfast Club',
    slug: 'breakfast-club',
    imageId: 'restaurant-14',
    cuisine: 'Breakfast',
    rating: 4.6,
    reviews: 1100,
    deliveryTime: 22,
    deliveryFee: 2.50,
    categories: ['Breakfast', 'American', 'Cafe'],
    menu: [
      {
        title: 'Classics',
        items: [
          { id: '1401', name: 'Pancakes Stack', description: 'Fluffy pancakes with syrup and butter.', price: 12.99, imageId: 'food-3' },
          { id: '1402', name: 'Eggs Benedict', description: 'Poached eggs, ham, on an English muffin with hollandaise.', price: 15.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '15',
    name: 'The Ramen Shop',
    slug: 'the-ramen-shop',
    imageId: 'restaurant-15',
    cuisine: 'Japanese',
    rating: 4.8,
    reviews: 1300,
    deliveryTime: 33,
    deliveryFee: 3.80,
    categories: ['Japanese', 'Ramen', 'Noodles'],
    menu: [
      {
        title: 'Ramen',
        items: [
          { id: '1501', name: 'Tonkotsu Ramen', description: 'Rich pork broth with chashu pork.', price: 16.99, imageId: 'food-5' },
          { id: '1502', name: 'Miso Ramen', description: 'Soybean paste broth with vegetables.', price: 15.99, imageId: 'food-6' },
        ],
      },
    ],
  },
  {
    id: '16',
    name: 'BBQ Central',
    slug: 'bbq-central',
    imageId: 'restaurant-16',
    cuisine: 'BBQ',
    rating: 4.5,
    reviews: 950,
    deliveryTime: 45,
    deliveryFee: 4.50,
    categories: ['BBQ', 'American', 'Grill'],
    menu: [
      {
        title: 'Meats',
        items: [
          { id: '1601', name: 'Pulled Pork Sandwich', description: 'Slow-smoked pulled pork on a brioche bun.', price: 14.99, imageId: 'food-7' },
          { id: '1602', name: 'Beef Brisket', description: 'Tender beef brisket, sold by the pound.', price: 28.99, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: '17',
    name: 'The Sweet Spot',
    slug: 'the-sweet-spot',
    imageId: 'restaurant-17',
    cuisine: 'Desserts',
    rating: 4.9,
    reviews: 2100,
    deliveryTime: 18,
    deliveryFee: 2.00,
    categories: ['Desserts', 'Bakery', 'Sweets'],
    menu: [
      {
        title: 'Cakes',
        items: [
          { id: '1701', name: 'Chocolate Lava Cake', description: 'Warm chocolate cake with a gooey center.', price: 8.99, imageId: 'food-9' },
          { id: '1702', name: 'New York Cheesecake', description: 'Classic creamy cheesecake.', price: 7.99, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: '18',
    name: 'Healthy Habits',
    slug: 'healthy-habits',
    imageId: 'restaurant-18',
    cuisine: 'Healthy',
    rating: 4.7,
    reviews: 780,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Healthy', 'Smoothies', 'Bowls'],
    menu: [
      {
        title: 'Smoothies',
        items: [
          { id: '1801', name: 'Green Detox Smoothie', description: 'Spinach, kale, apple, and banana.', price: 9.99, imageId: 'food-11' },
          { id: '1802', name: 'Berry Blast Smoothie', description: 'Mixed berries, yogurt, and honey.', price: 9.99, imageId: 'food-12' },
        ],
      },
    ],
  },
   {
    id: '19',
    name: 'Cluck-a-Doodle',
    slug: 'cluck-a-doodle',
    imageId: 'restaurant-19',
    cuisine: 'Chicken',
    rating: 4.6,
    reviews: 1300,
    deliveryTime: 25,
    deliveryFee: 3.50,
    categories: ['Chicken', 'Fast Food', 'American'],
    menu: [
      {
        title: 'Fried Chicken',
        items: [
          { id: '1901', name: '3-Piece Fried Chicken', description: 'Crispy and juicy fried chicken.', price: 12.99, imageId: 'food-44' },
          { id: '1902', name: 'Spicy Chicken Sandwich', description: 'A fiery chicken sandwich with pickles.', price: 9.99, imageId: 'food-45' },
        ],
      },
    ],
  },
  {
    id: '20',
    name: 'Boba Bliss',
    slug: 'boba-bliss',
    imageId: 'restaurant-20',
    cuisine: 'Bubble Tea',
    rating: 4.9,
    reviews: 2500,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bubble Tea', 'Drinks', 'Desserts'],
    menu: [
      {
        title: 'Milk Teas',
        items: [
          { id: '2001', name: 'Classic Milk Tea', description: 'Black tea with milk and tapioca pearls.', price: 5.50, imageId: 'food-46' },
          { id: '2002', name: 'Taro Milk Tea', description: 'Creamy taro flavor with boba.', price: 6.00, imageId: 'food-47' },
        ],
      },
    ],
  },
  {
    id: '21',
    name: 'The Halal Guys',
    slug: 'the-halal-guys',
    imageId: 'restaurant-21',
    cuisine: 'Halal',
    rating: 4.7,
    reviews: 5000,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Halal', 'Mediterranean', 'Street Food', 'Fast Food'],
    menu: [
      {
        title: 'Platters',
        items: [
          { id: '2101', name: 'Chicken & Gyro Combo', description: 'A mix of chicken and gyro meat over rice.', price: 14.99, imageId: 'food-48' },
          { id: '2102', name: 'Falafel Platter', description: 'Crispy falafel over rice with white sauce.', price: 12.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '22',
    name: 'Sublime Sandwiches',
    slug: 'sublime-sandwiches',
    imageId: 'restaurant-22',
    cuisine: 'Sandwiches',
    rating: 4.5,
    reviews: 600,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Sandwiches', 'Deli', 'Lunch'],
    menu: [
      {
        title: 'Hot Sandwiches',
        items: [
          { id: '2201', name: 'Philly Cheesesteak', description: 'Thinly-sliced beef with melted cheese and onions.', price: 13.99, imageId: 'food-49' },
          { id: '2202', name: 'Italian Meatball Sub', description: 'Meatballs in marinara with provolone.', price: 12.99, imageId: 'food-50' },
        ],
      },
    ],
  },
  {
    id: '23',
    name: 'Athens Grill',
    slug: 'athens-grill',
    imageId: 'restaurant-13',
    cuisine: 'Greek',
    rating: 4.8,
    reviews: 950,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Greek', 'Mediterranean', 'Healthy'],
    menu: [
      {
        title: 'Gyros',
        items: [
          { id: '2301', name: 'Lamb Gyro', description: 'Sliced lamb in a warm pita with tzatziki.', price: 11.99, imageId: 'food-1' },
          { id: '2302', name: 'Chicken Souvlaki Pita', description: 'Grilled chicken skewers in a pita.', price: 10.99, imageId: 'food-2' },
        ],
      },
    ],
  },
  {
    id: '24',
    name: 'Perfectly Pasta',
    slug: 'perfectly-pasta',
    imageId: 'restaurant-1',
    cuisine: 'Italian',
    rating: 4.6,
    reviews: 800,
    deliveryTime: 28,
    deliveryFee: 3.50,
    categories: ['Italian', 'Pasta', 'Noodle'],
    menu: [
      {
        title: 'Pasta',
        items: [
          { id: '2401', name: 'Fettuccine Alfredo', description: 'Creamy parmesan sauce over fettuccine.', price: 17.99, imageId: 'food-3' },
          { id: '2402', name: 'Pesto Gnocchi', description: 'Soft potato dumplings in a basil pesto sauce.', price: 18.99, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: '25',
    name: 'The Cake Box',
    slug: 'the-cake-box',
    imageId: 'restaurant-17',
    cuisine: 'Bakery',
    rating: 4.9,
    reviews: 1200,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Bakery', 'Desserts', 'Sweets'],
    menu: [
      {
        title: 'Cupcakes',
        items: [
          { id: '2501', name: 'Red Velvet Cupcake', description: 'Classic red velvet with cream cheese frosting.', price: 4.50, imageId: 'food-9' },
          { id: '2502', name: 'Chocolate Fudge Cupcake', description: 'Rich chocolate cupcake with fudge icing.', price: 4.50, imageId: 'food-10' },
        ],
      },
    ],
  },
  {
    id: '26',
    name: 'Waffle House',
    slug: 'waffle-house',
    imageId: 'restaurant-23',
    cuisine: 'Breakfast',
    rating: 4.4,
    reviews: 2500,
    deliveryTime: 20,
    deliveryFee: 3.50,
    categories: ['Breakfast', 'Waffles', 'American'],
    menu: [
      {
        title: 'Waffles',
        items: [
          { id: '2601', name: 'Classic Belgian Waffle', description: 'With whipped cream and strawberries.', price: 10.99, imageId: 'food-51' },
          { id: '2602', name: 'Chocolate Chip Waffle', description: 'Loaded with chocolate chips and syrup.', price: 11.99, imageId: 'food-52' },
        ],
      },
    ],
  },
  {
    id: '27',
    name: 'Pancake Palace',
    slug: 'pancake-palace',
    imageId: 'restaurant-24',
    cuisine: 'Breakfast',
    rating: 4.5,
    reviews: 1900,
    deliveryTime: 22,
    deliveryFee: 3.00,
    categories: ['Breakfast', 'Pancakes', 'American'],
    menu: [
      {
        title: 'Pancakes',
        items: [
          { id: '2701', name: 'Buttermilk Pancake Stack', description: 'A tall stack of fluffy pancakes.', price: 11.99, imageId: 'food-53' },
          { id: '2702', name: 'Blueberry Pancakes', description: 'Filled with fresh blueberries.', price: 12.99, imageId: 'food-54' },
        ],
      },
    ],
  },
  {
    id: '28',
    name: 'The Muffin Man',
    slug: 'the-muffin-man',
    imageId: 'restaurant-25',
    cuisine: 'Bakery',
    rating: 4.7,
    reviews: 800,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bakery', 'Breakfast', 'Coffee'],
    menu: [
      {
        title: 'Muffins',
        items: [
          { id: '2801', name: 'Blueberry Muffin', description: 'A classic muffin bursting with blueberries.', price: 3.99, imageId: 'food-55' },
          { id: '2802', name: 'Chocolate Chip Muffin', description: 'A sweet treat for any time of day.', price: 3.99, imageId: 'food-56' },
        ],
      },
    ],
  },
  {
    id: '29',
    name: 'Sunrise Eats',
    slug: 'sunrise-eats',
    imageId: 'restaurant-26',
    cuisine: 'Breakfast',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Breakfast', 'Brunch', 'American'],
    menu: [
      {
        title: 'Breakfast Plates',
        items: [
          { id: '2901', name: 'The Grand Slam', description: 'Pancakes, eggs, bacon, and sausage.', price: 16.99, imageId: 'food-57' },
          { id: '2902', name: 'Avocado Toast', description: 'Smashed avocado on sourdough with a poached egg.', price: 13.99, imageId: 'food-58' },
        ],
      },
    ],
  },
  {
    id: '30',
    name: 'Burger Barn',
    slug: 'burger-barn',
    imageId: 'restaurant-27',
    cuisine: 'Burgers',
    rating: 4.3,
    reviews: 750,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Burgers', 'American', 'Fast Food'],
    menu: [{ title: 'Burgers', items: [{ id: '3001', name: 'The Farmhand Burger', description: 'Double patty, cheddar, bacon, and a fried egg.', price: 15.99, imageId: 'food-9' }] }],
  },
  {
    id: '31',
    name: 'The Patty Shack',
    slug: 'the-patty-shack',
    imageId: 'restaurant-28',
    cuisine: 'Burgers',
    rating: 4.6,
    reviews: 900,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Burgers', 'American', 'Fast Food'],
    menu: [{ title: 'Burgers', items: [{ id: '3101', name: 'Shack Special', description: 'Single patty with secret sauce, lettuce, and tomato.', price: 10.99, imageId: 'food-10' }] }],
  },
  {
    id: '32',
    name: 'Grill Marks',
    slug: 'grill-marks',
    imageId: 'restaurant-29',
    cuisine: 'Burgers',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Burgers', 'American', 'Grill'],
    menu: [{ title: 'Burgers', items: [{ id: '3201', name: 'The Griller', description: 'Flame-grilled patty, smoked gouda, and onion jam.', price: 13.99, imageId: 'food-9' }] }],
  },
  {
    id: '33',
    name: 'Burgerology',
    slug: 'burgerology',
    imageId: 'restaurant-30',
    cuisine: 'Burgers',
    rating: 4.8,
    reviews: 1500,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Burgers', 'American', 'Gourmet'],
    menu: [{ title: 'Burgers', items: [{ id: '3301', name: 'The Einstein', description: 'Wagyu patty, truffle aioli, and arugula.', price: 18.99, imageId: 'food-10' }] }],
  },
  {
    id: '34',
    name: 'Espresso Yourself',
    slug: 'espresso-yourself',
    imageId: 'restaurant-31',
    cuisine: 'Coffee',
    rating: 4.7,
    reviews: 980,
    deliveryTime: 12,
    deliveryFee: 1.80,
    categories: ['Coffee', 'Cafe', 'Bakery'],
    menu: [{ title: 'Coffee', items: [{ id: '3401', name: 'Caramel Macchiato', description: 'Espresso, steamed milk, and caramel drizzle.', price: 5.25, imageId: 'food-33' }] }],
  },
  {
    id: '35',
    name: 'The Grind',
    slug: 'the-grind',
    imageId: 'restaurant-32',
    cuisine: 'Coffee',
    rating: 4.6,
    reviews: 850,
    deliveryTime: 10,
    deliveryFee: 1.50,
    categories: ['Coffee', 'Cafe'],
    menu: [{ title: 'Coffee', items: [{ id: '3501', name: 'Cold Brew', description: 'Slow-steeped, smooth, and strong.', price: 4.75, imageId: 'food-34' }] }],
  },
  {
    id: '36',
    name: 'Mocha Motion',
    slug: 'mocha-motion',
    imageId: 'restaurant-33',
    cuisine: 'Coffee',
    rating: 4.5,
    reviews: 700,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Coffee', 'Cafe', 'Desserts'],
    menu: [{ title: 'Coffee', items: [{ id: '3601', name: 'Iced Mocha', description: 'Espresso, chocolate, milk, and ice.', price: 5.50, imageId: 'food-33' }] }],
  },
  {
    id: '37',
    name: 'Slice of Heaven',
    slug: 'slice-of-heaven',
    imageId: 'restaurant-34',
    cuisine: 'Pizza',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 30,
    deliveryFee: 3.00,
    categories: ['Pizza', 'Italian'],
    menu: [{ title: 'Pizzas', items: [{ id: '3701', name: 'Meat Lover\'s Pizza', description: 'Pepperoni, sausage, bacon, and ham.', price: 19.99, imageId: 'food-30' }] }],
  },
  {
    id: '38',
    name: 'The Pizza Peel',
    slug: 'the-pizza-peel',
    imageId: 'restaurant-35',
    cuisine: 'Pizza',
    rating: 4.7,
    reviews: 1200,
    deliveryTime: 28,
    deliveryFee: 2.90,
    categories: ['Pizza', 'Italian', 'Gourmet'],
    menu: [{ title: 'Pizzas', items: [{ id: '3801', name: 'Prosciutto & Arugula Pizza', description: 'With shaved parmesan and a balsamic glaze.', price: 21.99, imageId: 'food-31' }] }],
  },
  {
    id: '39',
    name: 'Dough Boys',
    slug: 'dough-boys',
    imageId: 'restaurant-36',
    cuisine: 'Pizza',
    rating: 4.5,
    reviews: 880,
    deliveryTime: 25,
    deliveryFee: 2.50,
    categories: ['Pizza', 'Fast Food'],
    menu: [{ title: 'Pizzas', items: [{ id: '3901', name: 'BBQ Chicken Pizza', description: 'Chicken, red onions, cilantro, and BBQ sauce.', price: 18.99, imageId: 'food-30' }] }],
  },
  {
    id: '40',
    name: 'Zaiqa Halal',
    slug: 'zaiqa-halal',
    imageId: 'restaurant-37',
    cuisine: 'Halal',
    rating: 4.8,
    reviews: 1300,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Halal', 'Indian', 'Pakistani'],
    menu: [{ title: 'Grill', items: [{ id: '4001', name: 'Chicken Biryani', description: 'Flavorful rice dish with chicken.', price: 15.99, imageId: 'food-17' }] }],
  },
  {
    id: '41',
    name: 'Kabab Korner',
    slug: 'kabab-korner',
    imageId: 'restaurant-38',
    cuisine: 'Halal',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 28,
    deliveryFee: 3.00,
    categories: ['Halal', 'Middle Eastern', 'Grill'],
    menu: [{ title: 'Grill', items: [{ id: '4101', name: 'Beef Kabab Platter', description: 'Grilled beef skewers with rice and salad.', price: 18.99, imageId: 'food-48' }] }],
  },
  {
    id: '42',
    name: 'Royal Halal',
    slug: 'royal-halal',
    imageId: 'restaurant-39',
    cuisine: 'Halal',
    rating: 4.6,
    reviews: 950,
    deliveryTime: 32,
    deliveryFee: 3.80,
    categories: ['Halal', 'Indian'],
    menu: [{ title: 'Curries', items: [{ id: '4201', name: 'Lamb Karahi', description: 'Spicy lamb curry cooked in a wok.', price: 17.99, imageId: 'food-18' }] }],
  },
  {
    id: '43',
    name: 'NYC Street Cart',
    slug: 'nyc-street-cart',
    imageId: 'restaurant-21',
    cuisine: 'Halal',
    rating: 4.9,
    reviews: 3500,
    deliveryTime: 18,
    deliveryFee: 2.50,
    categories: ['Halal', 'Street Food', 'Fast Food'],
    menu: [{ title: 'Platters', items: [{ id: '4301', name: 'Lamb over Rice', description: 'Classic street food platter with white sauce.', price: 13.99, imageId: 'food-48' }] }],
  },
  {
    id: '44',
    name: 'The Fryer',
    slug: 'the-fryer',
    imageId: 'restaurant-40',
    cuisine: 'Chicken',
    rating: 4.5,
    reviews: 980,
    deliveryTime: 20,
    deliveryFee: 2.80,
    categories: ['Chicken', 'Fast Food'],
    menu: [{ title: 'Chicken', items: [{ id: '4401', name: 'Chicken Tenders Basket', description: 'Crispy chicken tenders with fries.', price: 11.99, imageId: 'food-44' }] }],
  },
  {
    id: '45',
    name: 'Wing World',
    slug: 'wing-world',
    imageId: 'restaurant-41',
    cuisine: 'Chicken',
    rating: 4.7,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Chicken', 'Wings', 'American'],
    menu: [{ title: 'Wings', items: [{ id: '4501', name: '10pc Buffalo Wings', description: 'Classic spicy buffalo wings with ranch.', price: 14.99, imageId: 'food-45' }] }],
  },
  {
    id: '46',
    name: 'The Coop',
    slug: 'the-coop',
    imageId: 'restaurant-42',
    cuisine: 'Chicken',
    rating: 4.6,
    reviews: 1150,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Chicken', 'Sandwiches', 'American'],
    menu: [{ title: 'Sandwiches', items: [{ id: '4601', name: 'Grilled Chicken Club', description: 'Grilled chicken, bacon, lettuce, and tomato.', price: 13.99, imageId: 'food-49' }] }],
  },
  {
    id: '47',
    name: 'Fowl Play',
    slug: 'fowl-play',
    imageId: 'restaurant-19',
    cuisine: 'Chicken',
    rating: 4.8,
    reviews: 1600,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Chicken', 'Gourmet', 'American'],
    menu: [{ title: 'Mains', items: [{ id: '4701', name: 'Roasted Half Chicken', description: 'Herb-roasted chicken with root vegetables.', price: 19.99, imageId: 'food-44' }] }],
  },
  {
    id: '48',
    name: 'Teatime',
    slug: 'teatime',
    imageId: 'restaurant-43',
    cuisine: 'Bubble Tea',
    rating: 4.8,
    reviews: 1900,
    deliveryTime: 12,
    deliveryFee: 1.90,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Fruit Teas', items: [{ id: '4801', name: 'Mango Green Tea', description: 'Fresh mango with green tea and popping boba.', price: 6.25, imageId: 'food-46' }] }],
  },
  {
    id: '49',
    name: 'The Boba Spot',
    slug: 'the-boba-spot',
    imageId: 'restaurant-44',
    cuisine: 'Bubble Tea',
    rating: 4.7,
    reviews: 1500,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Specials', items: [{ id: '4901', name: 'Brown Sugar Boba', description: 'Rich brown sugar syrup with fresh milk and tapioca.', price: 6.50, imageId: 'food-47' }] }],
  },
  {
    id: '50',
    name: 'Pearl Passion',
    slug: 'pearl-passion',
    imageId: 'restaurant-20',
    cuisine: 'Bubble Tea',
    rating: 4.6,
    reviews: 1200,
    deliveryTime: 18,
    deliveryFee: 2.20,
    categories: ['Bubble Tea', 'Drinks'],
    menu: [{ title: 'Milk Teas', items: [{ id: '5001', name: 'Oolong Milk Tea', description: 'Roasted oolong tea with creamy milk.', price: 5.75, imageId: 'food-46' }] }],
  },
   {
    id: '51',
    name: 'Chatterbox Cafe',
    slug: 'chatterbox-cafe',
    imageId: 'restaurant-43',
    cuisine: 'Bubble Tea',
    rating: 4.8,
    reviews: 1900,
    deliveryTime: 12,
    deliveryFee: 1.90,
    categories: ['Bubble Tea', 'Coffee', 'Desserts'],
    menu: [{ title: 'Fruit Teas', items: [{ id: '5101', name: 'Peach Oolong Tea', description: 'Fruity and refreshing with fruit bits.', price: 6.00, imageId: 'food-47' }] }],
  },
  {
    id: '52',
    name: 'Indian Tadka',
    slug: 'indian-tadka',
    imageId: 'restaurant-5',
    cuisine: 'Indian',
    rating: 4.7,
    reviews: 1800,
    deliveryTime: 38,
    deliveryFee: 4.20,
    categories: ['Indian', 'Curry'],
    menu: [{ title: 'Vegetarian', items: [{ id: '5201', name: 'Aloo Gobi', description: 'Cauliflower and potatoes in Indian spices.', price: 14.99, imageId: 'food-18' }] }],
  },
  {
    id: '53',
    name: 'Saffron Sun',
    slug: 'saffron-sun',
    imageId: 'restaurant-37',
    cuisine: 'Indian',
    rating: 4.9,
    reviews: 2200,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Indian', 'Fine Dining'],
    menu: [{ title: 'Mains', items: [{ id: '5301', name: 'Rogan Josh', description: 'Aromatic lamb curry.', price: 19.99, imageId: 'food-17' }] }],
  },
  {
    id: '54',
    name: 'Mumbai Street Food',
    slug: 'mumbai-street-food',
    imageId: 'restaurant-39',
    cuisine: 'Indian',
    rating: 4.6,
    reviews: 1400,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Indian', 'Street Food'],
    menu: [{ title: 'Snacks', items: [{ id: '5401', name: 'Pav Bhaji', description: 'Spiced vegetable mash with soft bread rolls.', price: 12.99, imageId: 'food-18' }] }],
  },
   {
    id: '55',
    name: 'Delhi Darbar',
    slug: 'delhi-darbar',
    imageId: 'restaurant-38',
    cuisine: 'Indian',
    rating: 4.8,
    reviews: 2500,
    deliveryTime: 40,
    deliveryFee: 4.50,
    categories: ['Indian', 'Mughlai', 'Fine Dining'],
    menu: [{ title: 'Tandoor', items: [{ id: '5501', name: 'Tandoori Chicken', description: 'Chicken marinated in yogurt and spices, cooked in a tandoor.', price: 18.99, imageId: 'food-17' }] }],
  },
  {
    id: '56',
    name: 'Sugar Rush',
    slug: 'sugar-rush',
    imageId: 'restaurant-45',
    cuisine: 'Desserts',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 15,
    deliveryFee: 2.20,
    categories: ['Desserts', 'Sweets'],
    menu: [{ title: 'Ice Cream', items: [{ id: '5601', name: 'Double Scoop Sundae', description: 'Your choice of two ice cream flavors with toppings.', price: 9.99, imageId: 'food-9' }] }],
  },
  {
    id: '57',
    name: 'Cookie Crumb',
    slug: 'cookie-crumb',
    imageId: 'restaurant-46',
    cuisine: 'Desserts',
    rating: 4.9,
    reviews: 2200,
    deliveryTime: 12,
    deliveryFee: 1.80,
    categories: ['Desserts', 'Cookies', 'Bakery'],
    menu: [{ title: 'Cookies', items: [{ id: '5701', name: 'Half Dozen Assorted Cookies', description: 'A mix of our best sellers.', price: 15.00, imageId: 'food-10' }] }],
  },
  {
    id: '58',
    name: 'El Jefe Taqueria',
    slug: 'el-jefe-taqueria',
    imageId: 'restaurant-47',
    cuisine: 'Mexican',
    rating: 4.8,
    reviews: 1600,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Mexican', 'Tacos'],
    menu: [{ title: 'Tacos', items: [{ id: '5801', name: 'Baja Fish Tacos', description: 'Crispy fish tacos with cabbage slaw and chipotle aioli.', price: 13.99, imageId: 'food-13' }] }],
  },
  {
    id: '59',
    name: 'La Fiesta',
    slug: 'la-fiesta',
    imageId: 'restaurant-48',
    cuisine: 'Mexican',
    rating: 4.7,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Mexican', 'Enchiladas', 'Margaritas'],
    menu: [{ title: 'Entrees', items: [{ id: '5901', name: 'Chicken Enchiladas', description: 'Corn tortillas filled with chicken, covered in green sauce.', price: 17.99, imageId: 'food-14' }] }],
  },
  {
    id: '60',
    name: 'Guac & Roll',
    slug: 'guac-and-roll',
    imageId: 'restaurant-49',
    cuisine: 'Mexican',
    rating: 4.6,
    reviews: 1100,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Mexican', 'Burritos', 'Bowls'],
    menu: [{ title: 'Bowls', items: [{ id: '6001', name: 'Burrito Bowl', description: 'Your choice of protein, rice, beans, and toppings.', price: 14.99, imageId: 'food-15' }] }],
  },
  {
    id: '61',
    name: 'Cantina Laredo',
    slug: 'cantina-laredo',
    imageId: 'restaurant-4',
    cuisine: 'Mexican',
    rating: 4.5,
    reviews: 950,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Mexican', 'Fajitas', 'Tex-Mex'],
    menu: [{ title: 'Fajitas', items: [{ id: '6101', name: 'Sizzling Steak Fajitas', description: 'Served with peppers, onions, tortillas, and sides.', price: 22.99, imageId: 'food-16' }] }],
  },
  {
    id: '62',
    name: 'Opa! Greek Taverna',
    slug: 'opa-greek-taverna',
    imageId: 'restaurant-50',
    cuisine: 'Greek',
    rating: 4.9,
    reviews: 1800,
    deliveryTime: 32,
    deliveryFee: 3.80,
    categories: ['Greek', 'Mediterranean'],
    menu: [{ title: 'Appetizers', items: [{ id: '6201', name: 'Saganaki (Flaming Cheese)', description: 'Pan-fried cheese, flambéed tableside.', price: 12.99, imageId: 'food-1' }] }],
  },
  {
    id: '63',
    name: 'The Olive Tree',
    slug: 'the-olive-tree',
    imageId: 'restaurant-51',
    cuisine: 'Greek',
    rating: 4.7,
    reviews: 1100,
    deliveryTime: 28,
    deliveryFee: 3.20,
    categories: ['Greek', 'Mediterranean', 'Healthy'],
    menu: [{ title: 'Mains', items: [{ id: '6301', name: 'Lamb Chops', description: 'Grilled lamb chops with lemon potatoes.', price: 25.99, imageId: 'food-2' }] }],
  },
  {
    id: '64',
    name: 'Zeus\'s Table',
    slug: 'zeuss-table',
    imageId: 'restaurant-13',
    cuisine: 'Greek',
    rating: 4.8,
    reviews: 1400,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Greek', 'Mediterranean', 'Seafood'],
    menu: [{ title: 'Seafood', items: [{ id: '6401', name: 'Grilled Octopus', description: 'Tender octopus grilled with olive oil and lemon.', price: 21.99, imageId: 'food-1' }] }],
  },
  {
    id: '65',
    name: 'The Sub Stop',
    slug: 'the-sub-stop',
    imageId: 'restaurant-52',
    cuisine: 'Sandwiches',
    rating: 4.6,
    reviews: 850,
    deliveryTime: 15,
    deliveryFee: 2.00,
    categories: ['Sandwiches', 'Deli', 'Fast Food'],
    menu: [{ title: 'Cold Subs', items: [{ id: '6501', name: 'Turkey Club', description: 'Turkey, bacon, lettuce, tomato on wheat.', price: 11.99, imageId: 'food-49' }] }],
  },
  {
    id: '66',
    name: 'Dagwood\'s Deli',
    slug: 'dagwoods-deli',
    imageId: 'restaurant-53',
    cuisine: 'Sandwiches',
    rating: 4.7,
    reviews: 950,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Sandwiches', 'Deli'],
    menu: [{ title: 'Specialty', items: [{ id: '6601', name: 'The Reuben', description: 'Corned beef, swiss cheese, sauerkraut on rye.', price: 14.99, imageId: 'food-50' }] }],
  },
  {
    id: '67',
    name: 'Melt Factory',
    slug: 'melt-factory',
    imageId: 'restaurant-54',
    cuisine: 'Sandwiches',
    rating: 4.8,
    reviews: 1200,
    deliveryTime: 22,
    deliveryFee: 2.80,
    categories: ['Sandwiches', 'Grilled Cheese', 'Comfort Food'],
    menu: [{ title: 'Grilled Cheese', items: [{ id: '6701', name: 'The Classic Melt', description: 'Cheddar and provolone on sourdough.', price: 9.99, imageId: 'food-49' }] }],
  },
  {
    id: '68',
    name: 'Panini Press',
    slug: 'panini-press',
    imageId: 'restaurant-22',
    cuisine: 'Sandwiches',
    rating: 4.7,
    reviews: 1050,
    deliveryTime: 18,
    deliveryFee: 2.60,
    categories: ['Sandwiches', 'Italian', 'Cafe'],
    menu: [{ title: 'Paninis', items: [{ id: '6801', name: 'Caprese Panini', description: 'Mozzarella, tomato, basil, and balsamic.', price: 12.99, imageId: 'food-50' }] }],
  },
  {
    id: '69',
    name: 'Pho King',
    slug: 'pho-king',
    imageId: 'restaurant-55',
    cuisine: 'Vietnamese',
    rating: 4.8,
    reviews: 1800,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Vietnamese', 'Noodles', 'Pho'],
    menu: [{ title: 'Pho', items: [{ id: '6901', name: 'Spicy Beef Pho', description: 'Beef broth with a kick of chili oil.', price: 14.99, imageId: 'food-28' }] }],
  },
  {
    id: '70',
    name: 'Saigon Shack',
    slug: 'saigon-shack',
    imageId: 'restaurant-56',
    cuisine: 'Vietnamese',
    rating: 4.7,
    reviews: 1500,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Vietnamese', 'Banh Mi', 'Sandwiches'],
    menu: [{ title: 'Banh Mi', items: [{ id: '7001', name: 'Classic Banh Mi', description: 'Pork, pâté, pickled vegetables, and cilantro on a baguette.', price: 10.99, imageId: 'food-49' }] }],
  },
  {
    id: '71',
    name: 'Hanoi House',
    slug: 'hanoi-house',
    imageId: 'restaurant-7',
    cuisine: 'Vietnamese',
    rating: 4.9,
    reviews: 2100,
    deliveryTime: 35,
    deliveryFee: 4.00,
    categories: ['Vietnamese', 'Fine Dining'],
    menu: [{ title: 'Mains', items: [{ id: '7101', name: 'Cha Ca La Vong', description: 'Grilled fish with dill and turmeric.', price: 24.99, imageId: 'food-29' }] }],
  },
  {
    id: '72',
    name: 'Mekong Kitchen',
    slug: 'mekong-kitchen',
    imageId: 'restaurant-57',
    cuisine: 'Vietnamese',
    rating: 4.6,
    reviews: 1200,
    deliveryTime: 30,
    deliveryFee: 3.20,
    categories: ['Vietnamese', 'Noodles'],
    menu: [{ title: 'Noodle Bowls', items: [{ id: '7201', name: 'Bun Thit Nuong', description: 'Grilled pork over vermicelli noodles with fresh herbs.', price: 15.99, imageId: 'food-28' }] }],
  }
];


export const allHomeFoods: Restaurant[] = [
  {
    id: 'hf1',
    name: "Maria's Kitchen",
    slug: 'marias-kitchen',
    imageId: 'food-1',
    cuisine: 'Homestyle Italian',
    rating: 4.9,
    reviews: 150,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Italian', 'Homemade', 'Pasta'],
    menu: [
      {
        title: 'Family Recipes',
        items: [
          { id: 'hf101', name: 'Grandma\'s Lasagna', description: 'Layers of pasta, ricotta, and bolognese sauce.', price: 18.00, imageId: 'food-3' },
          { id: 'hf102', name: 'Chicken Parmesan', description: 'Breaded chicken with marinara and mozzarella.', price: 17.50, imageId: 'food-4' },
        ],
      },
    ],
  },
  {
    id: 'hf2',
    name: 'Chen\'s Dumplings',
    slug: 'chens-dumplings',
    imageId: 'food-2',
    cuisine: 'Chinese',
    rating: 4.8,
    reviews: 210,
    deliveryTime: 25,
    deliveryFee: 2.99,
    categories: ['Chinese', 'Dumplings', 'Homemade'],
    menu: [
      {
        title: 'Dumplings',
        items: [
          { id: 'hf201', name: 'Pork & Chive Dumplings (12pcs)', description: 'Hand-wrapped and pan-fried.', price: 15.00, imageId: 'food-5' },
          { id: 'hf202', name: 'Veggie Dumplings (12pcs)', description: 'Filled with mushrooms, cabbage, and carrots.', price: 14.00, imageId: 'food-6' },
        ],
      },
    ],
  },
  {
    id: 'hf3',
    name: "Javier's Tacos",
    slug: 'javiers-tacos',
    imageId: 'food-13',
    cuisine: 'Authentic Mexican',
    rating: 4.9,
    reviews: 300,
    deliveryTime: 20,
    deliveryFee: 2.50,
    categories: ['Mexican', 'Tacos', 'Homemade'],
    menu: [
      {
        title: 'Street Tacos',
        items: [
          { id: 'hf301', name: 'Carne Asada Tacos (3)', description: 'Marinated grilled steak on corn tortillas.', price: 12.00, imageId: 'food-13' },
          { id: 'hf302', name: 'Cochinita Pibil Tacos (3)', description: 'Slow-roasted pork with pickled onions.', price: 12.00, imageId: 'food-14' },
        ],
      },
    ],
  },
  {
    id: 'hf4',
    name: 'Healthy Home Bowls',
    slug: 'healthy-home-bowls',
    imageId: 'food-22',
    cuisine: 'Healthy Bowls',
    rating: 4.7,
    reviews: 95,
    deliveryTime: 15,
    deliveryFee: 4.00,
    categories: ['Healthy', 'Vegan', 'Bowls'],
    menu: [
      {
        title: 'Nourish Bowls',
        items: [
          { id: 'hf401', name: 'Quinoa & Roasted Veggie Bowl', description: 'With lemon-tahini dressing.', price: 16.00, imageId: 'food-22' },
          { id: 'hf402', name: 'Mediterranean Chicken Bowl', description: 'Grilled chicken, feta, olives, and couscous.', price: 17.00, imageId: 'food-23' },
        ],
      },
    ],
  },
  {
    id: 'hf5',
    name: "Priya's Indian Feast",
    slug: 'priyas-indian-feast',
    imageId: 'food-17',
    cuisine: 'Homestyle Indian',
    rating: 4.8,
    reviews: 180,
    deliveryTime: 35,
    deliveryFee: 3.75,
    categories: ['Indian', 'Curry', 'Homemade'],
    menu: [
      {
        title: 'Curries',
        items: [
          { id: 'hf501', name: 'Homestyle Chicken Curry', description: 'Aromatic and medium spicy.', price: 17.00, imageId: 'food-17' },
          { id: 'hf502', name: 'Dal Makhani', description: 'Creamy black lentils.', price: 15.00, imageId: 'food-18' },
        ],
      },
    ],
  },
  {
    id: 'hf6',
    name: 'Brenda\'s BBQ',
    slug: 'brendas-bbq',
    imageId: 'food-7',
    cuisine: 'Southern BBQ',
    rating: 4.9,
    reviews: 250,
    deliveryTime: 45,
    deliveryFee: 5.00,
    categories: ['BBQ', 'American', 'Homemade'],
    menu: [
      {
        title: 'BBQ Plates',
        items: [
          { id: 'hf601', name: 'Pulled Pork Plate', description: 'With coleslaw and cornbread.', price: 19.00, imageId: 'food-7' },
          { id: 'hf602', name: 'Smoked Ribs (Half Rack)', description: 'Fall-off-the-bone tender.', price: 22.00, imageId: 'food-8' },
        ],
      },
    ],
  },
  {
    id: 'hf7',
    name: 'Mama Kim\'s Korean',
    slug: 'mama-kims-korean',
    imageId: 'food-24', // Placeholder
    cuisine: 'Korean',
    rating: 4.8,
    reviews: 190,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Korean', 'Homemade', 'Spicy'],
    menu: [
      {
        title: 'Main Dishes',
        items: [
          { id: 'hf701', name: 'Bibimbap', description: 'Mixed rice with vegetables, beef, and a fried egg.', price: 18.00, imageId: 'food-24' },
          { id: 'hf702', name: 'Kimchi Jjigae', description: 'Spicy kimchi stew with pork and tofu.', price: 17.00, imageId: 'food-25' },
        ],
      },
    ],
  },
    {
    id: 'hf8',
    name: 'Sophie\'s Soups',
    slug: 'sophies-soups',
    imageId: 'food-38',
    cuisine: 'Soups & Stews',
    rating: 4.9,
    reviews: 120,
    deliveryTime: 20,
    deliveryFee: 3.00,
    categories: ['Soup', 'Comfort Food', 'Homemade'],
    menu: [
      {
        title: 'Hearty Soups',
        items: [
          { id: 'hf801', name: 'Tomato Basil Soup', description: 'Creamy and rich, served with a side of bread.', price: 12.00, imageId: 'food-38' },
          { id: 'hf802', name: 'Chicken Noodle Soup', description: 'Classic comfort in a bowl.', price: 13.00, imageId: 'food-29' },
        ],
      },
    ],
  },
  {
    id: 'hf9',
    name: 'Baker Ben\'s Breads',
    slug: 'baker-bens-breads',
    imageId: 'food-19',
    cuisine: 'Artisan Bakery',
    rating: 4.9,
    reviews: 280,
    deliveryTime: 15,
    deliveryFee: 4.00,
    categories: ['Bakery', 'Bread', 'Homemade'],
    menu: [
      {
        title: 'Freshly Baked',
        items: [
          { id: 'hf901', name: 'Sourdough Loaf', description: 'Naturally leavened and crusty.', price: 9.00, imageId: 'food-19' },
          { id: 'hf902', name: 'Chocolate Babka', description: 'Sweet braided bread with chocolate filling.', price: 14.00, imageId: 'food-27' },
        ],
      },
    ],
  },
  {
    id: 'hf10',
    name: 'Thai by Ton',
    slug: 'thai-by-ton',
    imageId: 'food-36',
    cuisine: 'Authentic Thai',
    rating: 4.8,
    reviews: 165,
    deliveryTime: 30,
    deliveryFee: 3.25,
    categories: ['Thai', 'Homemade', 'Spicy'],
    menu: [
      {
        title: 'Thai Favorites',
        items: [
          { id: 'hf1001', name: 'Green Curry with Chicken', description: 'Homemade green curry paste, coconut milk, and chicken.', price: 17.50, imageId: 'food-37' },
          { id: 'hf1002', name: 'Drunken Noodles (Pad Kee Mao)', description: 'Spicy stir-fried flat noodles with basil.', price: 16.50, imageId: 'food-36' },
        ],
      },
    ],
  },
  {
    id: 'hf11',
    name: 'Elena\'s Greek Kitchen',
    slug: 'elenas-greek-kitchen',
    imageId: 'food-21',
    cuisine: 'Greek',
    rating: 4.9,
    reviews: 195,
    deliveryTime: 30,
    deliveryFee: 3.50,
    categories: ['Greek', 'Mediterranean', 'Homemade'],
    menu: [
      {
        title: 'Greek Specialties',
        items: [
          { id: 'hf1101', name: 'Moussaka', description: 'Layered eggplant, minced meat, and béchamel sauce.', price: 19.00, imageId: 'food-21' },
          { id: 'hf1102', name: 'Spanakopita (Spinach Pie)', description: 'Flaky phyllo pastry with spinach and feta.', price: 10.00, imageId: 'food-22' },
        ],
      },
    ],
  },
  {
    id: 'hf12',
    name: 'Frank\'s Famous Chili',
    slug: 'franks-famous-chili',
    imageId: 'food-24', // Placeholder
    cuisine: 'American Comfort',
    rating: 4.7,
    reviews: 88,
    deliveryTime: 25,
    deliveryFee: 3.00,
    categories: ['Comfort Food', 'American', 'Homemade'],
    menu: [
      {
        title: 'Chili Bowls',
        items: [
          { id: 'hf1201', name: 'Classic Beef Chili', description: 'Hearty and spicy, served with sour cream and cheese.', price: 15.00, imageId: 'food-24' },
          { id: 'hf1202', name: 'Vegetarian Three-Bean Chili', description: 'A flavorful mix of beans and spices.', price: 14.00, imageId: 'food-25' },
        ],
      },
    ],
  },
];

    